/*
 * SPDX-FileCopyrightText: 2026 The tetherpoint Authors
 * SPDX-License-Identifier: Apache-2.0
 *
 * tethermesh.h -- C interface to the tethermesh protocol library.
 *
 * GENERATED BY CBINDGEN. DO NOT EDIT.
 * Regenerate with tools/generate_header.sh; tools/check_docs.sh fails if this
 * file and the crate have drifted apart. It was maintained by hand until
 * 2026-08-18, and the reason it no longer is: a hand-written header drifts
 * SILENTLY, and the symptom is a field read at the wrong offset that presents
 * as a protocol bug rather than a build problem.
 *
 * tm_check_layout() still exists and is still worth calling at startup. It is
 * now a second line of defence rather than the first -- it catches a stale
 * header linked against a rebuilt library, which generation cannot.
 *
 * WHAT THIS LIBRARY IS AND IS NOT
 * -------------------------------
 * It is the Meshtastic protocol: framing, channel crypto, PKI direct messages,
 * and the routing decision. It is not a radio driver, has no clock, allocates
 * nothing, and holds no global state. Everything time-dependent takes `now_us`
 * as an argument, because a no_std library cannot portably know the time and a
 * hidden clock would be untestable.
 *
 * PREBUILT BINARIES
 * -----------------
 * If you encounter ABI boundary issues with a prebuilt library, REBUILD FROM
 * SOURCE. That is not a disclaimer of quality; float ABI variants, toolchain
 * versions and calling-convention flags differ between build environments in
 * ways a published artifact cannot anticipate, and rebuilding resolves them
 * definitively.
 *
 * MEMORY AND STACK
 * ----------------
 * The context is yours to place. tm_ctx_size() reports how much; putting it in
 * .bss means the linker checks the budget, where a task-stack local means a
 * stack overflow discovered in the field. On a Cortex-M with no MPU region that
 * overflow corrupts an adjacent task's memory and surfaces later as something
 * unrelated.
 *
 * Budget ~1 KB of stack for this library's own call depth, measured at 696
 * bytes worst case in CCM decrypt. FreeRTOS's configMINIMAL_STACK_SIZE of 512
 * bytes is smaller than one decrypt.
 *
 * One task per context needs no lock. Sharing one needs yours; nothing here can
 * enforce it, because Send/Sync do not cross this boundary.
 *
 * THE HAZARD THIS ABI IS DESIGNED AROUND
 * --------------------------------------
 * Meshtastic's PSK field is polymorphic: 0 bytes means no crypto, 16 or 32
 * bytes is a key, and 1 byte is a shorthand INDEX where 1 names the default key
 * and 2..10 name it with 1..9 added to its last byte. A function taking
 * (const uint8_t *, size_t) cannot tell them apart, and the failure is silent:
 * the first consumer written against this library passed the index {1} where
 * the expanded key was wanted and computed channel hash 0x0b instead of 0x08 --
 * wrong, unreported, and on the most common channel on the network. So there is
 * no such function. Build a key by naming which form you have, and pass
 * tm_key_t everywhere after.
 */

/* Opaque by design: size them with tm_ctx_size()/tm_outbox_size() and align
 * them with tm_ctx_align()/tm_outbox_align(), then place the storage yourself.
 * Their layout is not part of the ABI and will change without a version bump. */
struct tm_ctx_t;
struct tm_outbox_t;
typedef struct tm_ctx_t tm_ctx_t;
typedef struct tm_outbox_t tm_outbox_t;


#ifndef TETHERMESH_H
#define TETHERMESH_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/*
 Bumped on any change to a signature, struct layout, or enum value here.

 Checked at init by the C side. A stale header against a rebuilt library is
 otherwise silent and produces symptoms attributable to anything at all;
 four bytes to make it impossible is a trade worth taking every time.
 */
#define TM_ABI_VERSION 7

/*
 Status codes, defined once so the ABI and its tests cannot disagree.

 These are the values `tethermesh.h` publishes. A second definition in the
 shim would be a place for the two to drift apart silently.
 */
#define TM_OK 0

/*
 A null pointer, a malformed input, or a value outside its documented range.
 */
#define TM_E_ARG -1

/*
 The caller's header disagrees with the linked library about the ABI.
 */
#define TM_E_ABI -2

/*
 A buffer too small, or no free slot.
 */
#define TM_E_SHORT -3

/*
 Key material of a length the protocol does not define.
 */
#define TM_E_BAD_KEY_LEN -4

/*
 A channel index outside the range the shorthand defines.
 */
#define TM_E_BAD_INDEX -5

/*
 A retry policy more aggressive than the measured ceiling.
 */
#define TM_E_TOO_AGGRESSIVE -6

/*
 A direct message whose authentication tag does not verify.

 Its own code, because it is the one failure here that means someone may be
 lying to you rather than that something is misconfigured. Never retry it and
 never use the buffer: a forged message decrypts to *something*.
 */
#define TM_E_UNAUTHENTIC -7

/*
 A peer public key that drives the shared secret to zero.

 Distinct from [`TM_E_UNAUTHENTIC`] and from a hardware fault because the
 three call for opposite responses. This one is chosen deliberately by an
 attacker and is never retryable.
 */
#define TM_E_SMALL_ORDER -8

#define TM_SUPPRESSED_NONE 0

#define TM_SUPPRESSED_DUPLICATE 1

#define TM_SUPPRESSED_HOP_LIMIT 2

#define TM_SUPPRESSED_RELAYED_BY_OTHER 3

#define TM_SUPPRESSED_DUTY_BUDGET 4

/*
 An expanded channel key. Always 16 bytes, always ready to use.

 The point of the type is that it cannot be confused with the 1-byte
 shorthand: there is no way to obtain one except through a constructor that
 names which form it was given.
 */
typedef struct tm_key_t {
  uint8_t bytes[16];
} tm_key_t;

/*
 What a received frame turned out to be.

 The shape mirrors the radio driver's callback deliberately: a frame and an
 SNR go in, and nothing here knows what a chirp is. That keeps this library
 usable over any PHY that can carry the bytes.
 */
typedef struct tm_rx_t {
  uint32_t from;
  uint32_t to;
  uint32_t id;
  uint8_t hop_limit;
  uint8_t want_ack;
  uint8_t channel_hash;
  uint8_t duplicate;
  /*
   1 if the caller should rebroadcast after waiting.
   */
  uint8_t relay;
  /*
   Draw uniformly in `[0, relay_window_slots)` and wait that many slots.
   Deterministic waiting is what makes a mesh collide with itself.
   */
  uint8_t relay_window_slots;
  /*
   `hop_limit` already decremented, for the frame to rebroadcast.
   */
  uint8_t relay_hop_limit;
  /*
   Reason when `relay` is 0, for diagnostics.
   */
  uint8_t suppressed;
} tm_rx_t;

/*
 What a node publishes about itself: the fields of a `User`.

 Pointer/length pairs rather than fixed arrays, because every one of these is
 variable-length on the wire and a fixed array would force this header to
 invent a maximum the protocol does not define.

 A null pointer or a zero length omits the field, which is what proto3 does
 with a default. **`macaddr` is the trap.** It has been deprecated since
 2.1.x and firmware 2.7.26 still puts it on the wire as six zero bytes in
 every `User` in the corpus, so a `User` that drops it re-encodes shorter
 than the reference produced. Pass the six zero bytes to match what is
 actually emitted; deprecated in the schema is not absent from the wire.
 */
typedef struct tm_user_t {
  /*
   Conventionally `!` followed by the node number in lowercase hex.
   */
  const uint8_t *id;
  size_t id_len;
  const uint8_t *long_name;
  size_t long_name_len;
  /*
   Conventionally four characters.
   */
  const uint8_t *short_name;
  size_t short_name_len;
  /*
   32 bytes from [`tm_x25519_public`]. Omitted when absent, and a peer that
   does not receive it cannot address this node by direct message.
   */
  const uint8_t *public_key;
  size_t public_key_len;
  /*
   Six bytes. See the note above before deciding to leave it out.
   */
  const uint8_t *macaddr;
  size_t macaddr_len;
  uint32_t hw_model;
  uint32_t role;
} tm_user_t;

/*
 A message key agreed with one peer: SHA-256 over the raw X25519 secret.

 A distinct type for the same reason `tm_key_t` is one — it is not
 interchangeable with a channel key, and the two are the same shape in C. A
 channel key is 16 bytes of AES-128 shared by everyone on the channel; this
 is 32 bytes of AES-256 shared with exactly one peer, and passing one where
 the other belongs would fail as "the radio is broken".

 **The full SHA-256 output, not truncated to 128 bits.** That is measured, in
 `tests/captures/pki_dm_record.json`, and it is the sort of parameter that is
 guessed wrong and then produces garbage with nothing to say why.
 */
typedef struct tm_pki_key_t {
  uint8_t bytes[32];
} tm_pki_key_t;

/*
 A decoded `Data` wrapper. Slices borrow from the buffer passed to
 [`tm_data_decode`] and are valid only while it is.

 Carries the fields a consumer acts on, not the whole schema. Adding one is
 an ABI change and should be, so the set here is deliberately the measured
 subset rather than everything the wire can hold.
 */
typedef struct tm_data_t {
  uint32_t portnum;
  const uint8_t *payload;
  size_t payload_len;
  /*
   The sender wants a reply. Answer it addressed to the sender, and do not
   set this on the answer -- two nodes each asking the other is a loop that
   costs shared airtime and resolves nothing.
   */
  uint8_t want_response;
  /*
   Identifier of the request this answers, 0 when it answers nothing.
   */
  uint32_t request_id;
} tm_data_t;

/*
 The 16-byte cleartext header, decoded.

 Every field is on the wire in the clear, so this needs no key and makes no
 routing decision — it is a parse, not an observation. [`tm_rx_observe`] is
 the one that decides, and it mutates history in doing so.

 **This exists because a consumer needed these three fields before it could
 call anything else** — who sent a frame, which packet it is, and who
 relayed it — and with no way to ask, it read bytes 4..8, 8..12 and 15 out of
 the frame itself. That put this crate's wire layout in someone else's source
 with nothing keeping the two in step. The offsets belong here.

 **It travels in the clear and nothing authenticates it.** Any relay can alter
 it and any listener can forge one; `hop_limit`, `channel` and `relay_node`
 are routing hints, never evidence. See `header.rs`.
 */
typedef struct tm_header_t {
  uint32_t to;
  uint32_t from;
  uint32_t id;
  uint8_t hop_limit;
  /*
   Equal to `hop_limit` on a frame nobody has forwarded. **That comparison
   is how directness is decided** — a relayed copy has been decremented.
   */
  uint8_t hop_start;
  uint8_t channel_hash;
  /*
   Low byte of the next hop's node number, 0 when unset.
   */
  uint8_t next_hop;
  /*
   Low byte of the node that transmitted this copy — the originator on a
   frame nobody has forwarded, the relay otherwise.
   */
  uint8_t relay_node;
  uint8_t want_ack;
  uint8_t via_mqtt;
} tm_header_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t tm_abi_version(void);

/*
 Verify the C header's view of struct layout matches this crate's.

 **The header is generated now** (`tools/generate_header.sh`, gated by
 `tools/check_header.sh`), so the drift this was built to mitigate is largely
 gone. It was hand-written until 2026-08-18 because cbindgen was not
 installed, and a hand-written header against a changing crate drifts
 silently -- a field added on the Rust side shifts every offset after it, and
 C then reads garbage that looks like a protocol bug.

 Keep calling it anyway. Generation and this check answer **different
 questions**: generation guarantees the committed header matches the crate at
 build time, while this catches a *stale header linked against a rebuilt
 library* -- a shipped binary and a header from a different version, which no
 amount of generation can see.

 It compares sizes, so it catches a field added, removed or resized and does
 **not** catch two same-width fields swapped. Stated plainly so nobody reads
 it as more than it is.
 */
int32_t tm_check_layout(size_t sizeof_rx,
                        size_t sizeof_key,
                        size_t sizeof_user,
                        size_t sizeof_pki_key,
                        size_t sizeof_data,
                        size_t sizeof_header);

/*
 Expand the 1-byte shorthand: `1` is the default key, `2..=10` add 1..9 to its
 last byte. `0` means no crypto and is rejected here rather than silently
 producing a key, because a caller asking for a key when there is none is
 making a mistake worth surfacing.
 # Safety

 `out` must be null or a valid, aligned, writable `tm_key_t`.

 **This is `unsafe` because it writes through `out`, and it was not always.**
 It was declared safe while dereferencing a raw pointer, which is unsound:
 the null check covers null and nothing covers a dangling or misaligned
 pointer, so a Rust caller could reach undefined behaviour with no `unsafe`
 at the call site. Every other pointer-taking function in this ABI was
 already `unsafe`; this one was the exception. **The C ABI is unchanged** —
 `unsafe` is a Rust-side obligation and does not affect the symbol, the
 calling convention or the header — so no version bump is owed for it.
 */
int32_t tm_key_from_index(uint8_t index, struct tm_key_t *out);

/*
 Take an explicit key. 16 bytes is used as-is; 32 bytes is accepted because
 the protocol allows AES-256 channels, and its first 16 bytes are what this
 path needs. Any other length is an error rather than a truncation.
 */
int32_t tm_key_from_bytes(const uint8_t *psk, size_t len, struct tm_key_t *out);

/*
 Channel hash over a name and an already-expanded key.

 Note the name: the *modem preset* name is what gets hashed, not whatever the
 config message carries. Proto3 omits defaults, so the primary channel's name
 is absent on the wire, and folding the empty string yields `0x02` where real
 traffic shows `0x08`. Passing "LongFast" is correct for the default channel.
 */
uint8_t tm_channel_hash(const uint8_t *name, size_t name_len, const struct tm_key_t *key);

size_t tm_ctx_size(void);

size_t tm_ctx_align(void);

/*
 Initialise a caller-provided context.

 `abi` must be `tm_abi_version()` as the *header* saw it; a mismatch fails
 here rather than misbehaving later.
 */
int32_t tm_ctx_init(tm_ctx_t *ctx, uint32_t abi, uint32_t node_num);

/*
 Observe a received frame: parse its header, note it in history, and decide
 whether to relay.

 `snr_q4` is signed quarter-dB — the unit the radio reports and the unit the
 protocol carries, so nothing rescales it anywhere.

 `heard_relayed` is the caller's to determine and cannot be inferred here:
 it means "I already have this frame queued for relay and have now heard
 somebody else send it." The library holds no pending-transmission set,
 because it has neither a clock nor a radio -- `DISTRIBUTION.md` puts
 scheduling firmly on the caller's side. `should_relay`'s contract says as
 much: *wait a backoff drawn from this window, then transmit **if nobody else
 did***. Passing 0 always makes that clause unenforceable and the
 `AlreadyRelayedByAnother` suppression unreachable.

 This does **not** decrypt. Relaying does not require the key, and stock nodes
 are observed forwarding frames on channels they cannot read; a function that
 demanded a key to make a routing decision would misdescribe the protocol.
 */
int32_t tm_rx_observe(tm_ctx_t *ctx,
                      const uint8_t *frame_ptr,
                      size_t frame_len,
                      int16_t snr_q4,
                      uint32_t airtime_us,
                      uint64_t now_us,
                      uint8_t heard_relayed,
                      struct tm_rx_t *out);

/*
 Decrypt a frame in place and hand back the plaintext payload.

 Separate from `tm_rx_observe` because the two answer different questions and
 need different inputs: routing needs the header alone, decryption needs a
 key. Keeping them apart is what lets a relay work without one.
 */
int32_t tm_frame_decrypt(uint8_t *frame_ptr,
                         size_t frame_len,
                         const struct tm_key_t *key,
                         const uint8_t **payload_out,
                         size_t *payload_len_out);

/*
 Encode a broadcast text message into a ready-to-transmit frame.

 Text is portnum 1 (TEXT_MESSAGE_APP). `to` is normally 0xFFFFFFFF, which is
 how a stock node recognises a broadcast.

 `id` is the caller's to choose and must not repeat: every receiver on the
 mesh keys duplicate suppression on `(from, id)`, so a reused identifier is
 silently dropped by everyone who saw the first one. tethermesh's
 `packet_id::PacketIdSource` exists for this and refuses to issue past a
 durable high-water mark, because an identifier handed out before it is
 persisted is exactly the one reissued after an unclean restart.

 `hop_start` is set equal to `hop_limit`, which is what a node originating a
 packet does -- the pair is how receivers compute how far a frame has
 travelled.

 Returns the frame length, or negative on error.
 */
int32_t tm_text_encode(uint32_t from,
                       uint32_t to,
                       uint32_t id,
                       uint8_t hop_limit,
                       uint8_t channel_hash,
                       uint8_t want_ack,
                       const struct tm_key_t *key,
                       const uint8_t *text,
                       size_t text_len,
                       uint8_t *out,
                       size_t out_cap);

/*
 Patch a received frame in place so it can be rebroadcast.

 Two fields change and nothing else: `hop_limit` takes the decremented value
 from [`tm_rx_observe`], and `relay_node` becomes the low byte of this node's
 number. Everything else -- id, from, the encrypted body -- is carried
 verbatim, which is what makes it the *same* packet rather than a new one.
 Rewriting `from` or `id` would defeat duplicate suppression across the whole
 mesh and multiply the frame instead of forwarding it.

 `relay_node` being a one-byte truncation of the node number is recorded in
 WIRE_REFERENCE.md from captured traffic, and confirmed here: a stock node
 relaying our packet stamped 0x64, the low byte of its own 0x3369e764.
 */
int32_t tm_relay_prepare(uint8_t *frame_ptr,
                         size_t frame_len,
                         uint8_t relay_hop_limit,
                         uint32_t our_node_num);

/*
 Record a packet we originated, so it is suppressed if it comes back.

 Transmitting records nothing in history, so a node's own packet returning
 from someone else's relay reports `duplicate = 0`. The only thing preventing
 a loop is then the caller comparing `from` against its own node number --
 one check deep, for a failure that multiplies traffic across an entire mesh.

 Calling this after transmitting makes the ordinary duplicate machinery cover
 the case too, which is a second mechanism rather than a louder version of
 the first.
 */
int32_t tm_note_originated(tm_ctx_t *ctx, uint32_t from, uint32_t id);

size_t tm_outbox_size(void);

size_t tm_outbox_align(void);

/*
 Initialise a caller-provided outbox.

 Pass `max_attempts = 0` and `interval_us = 0` to take the measured ceiling
 (3 attempts, 7 s). Any explicit policy must be no more aggressive than that:
 more attempts, or a shorter interval, returns [`TM_E_TOO_AGGRESSIVE`] rather
 than being quietly clamped -- a clamp would leave the caller believing it had
 configured something it had not.
 */
int32_t tm_outbox_init(tm_outbox_t *ob, uint32_t abi, uint8_t max_attempts, uint32_t interval_us);

/*
 Track a frame that has **already been transmitted once**.

 The first transmission is the caller's and its airtime is the caller's to
 charge; this records the frame so later attempts can be made from it.

 Returns [`TM_OK`], or [`TM_E_SHORT`] when every slot is in use.
 */
int32_t tm_outbox_track(tm_outbox_t *ob,
                        const uint8_t *frame_ptr,
                        size_t frame_len,
                        uint64_t now_us);

/*
 Retire the entry an acknowledgement refers to.

 Returns 1 if something matched, 0 if nothing did. **Zero is ordinary, not an
 error** -- the acknowledgement may be for a frame already retired, or for
 another node entirely.
 */
int32_t tm_outbox_acknowledge(tm_outbox_t *ob, uint32_t request_id);

/*
 How many frames are still awaiting acknowledgement.
 */
int32_t tm_outbox_pending(const tm_outbox_t *ob);

/*
 Drop one entry that has exhausted every attempt, reporting what it was.

 Returns 1 and fills `out_from`/`out_id` when something was given up on, 0
 when nothing has. Call until it returns 0.

 Giving up is reported rather than discarded because "this was never
 acknowledged" is the single most useful thing this module produces -- it is
 the only evidence available that a frame did not arrive.
 */
int32_t tm_outbox_reap(tm_outbox_t *ob, uint64_t now_us, uint32_t *out_from, uint32_t *out_id);

/*
 The next frame due for retransmission, copied into `out`.

 Returns its length and writes the attempt number to `out_attempt`, or 0 when
 nothing is due, everything is exhausted, or the duty budget would not permit
 the airtime.

 **A caller that takes a frame must transmit it.** The attempt is marked and
 the next one scheduled by this call, so discarding the result silently
 consumes a retry. The duty budget is deliberately NOT charged here -- the
 caller charges on actual transmission, matching `should_relay`, because
 charging here would bill a node for a frame it had not sent.
 */
int32_t tm_outbox_next_due(tm_outbox_t *ob,
                           tm_ctx_t *ctx,
                           uint64_t now_us,
                           uint32_t airtime_us,
                           uint8_t *out,
                           size_t out_cap,
                           uint8_t *out_attempt);

/*
 Read a decrypted payload as an acknowledgement, if it is one.

 Returns 1 and fills the outputs when it is, 0 when it is not.

 `out_status` is the `Routing` status: 0 is acceptance. **A rejection retires
 the pending entry exactly as an acceptance does** -- either way no further
 retransmission will help -- so it is reported for the caller to log, not for
 the outbox to act on differently.
 */
int32_t tm_acknowledges(const uint8_t *payload,
                        size_t payload_len,
                        uint32_t *out_request_id,
                        uint32_t *out_status);

/*
 Whether a received frame is addressed to us and asks to be acknowledged.

 Reads the header only; the body does not need decrypting to answer it.
 */
int32_t tm_wants_ack(const uint8_t *frame_ptr, size_t frame_len, uint32_t our_node_num);

/*
 Build and encrypt an acknowledgement of `request_id`, addressed to `to`.

 Returns the frame length, or negative on error.

 Two measured facts are baked in and neither is obvious. The success payload
 is the two bytes `18 00` -- `Routing` field 3 encoded EXPLICITLY, where
 proto3 would normally omit a zero varint, so an acknowledgement built from
 first principles carries an empty payload and on the evidence would not be
 recognised. And the reply travels CHANNEL-encrypted even when acknowledging a
 PKI message: the acknowledgement does not inherit the request's encryption
 mode, which is the sort of thing that fails looking like a radio fault.

 `want_ack` is deliberately not set on it. Acknowledging an acknowledgement
 spends shared airtime for no delivery benefit.
 */
int32_t tm_ack_encode(uint32_t from,
                      uint32_t to,
                      uint32_t id,
                      uint32_t request_id,
                      uint8_t hop_limit,
                      uint8_t channel_hash,
                      const struct tm_key_t *key,
                      uint8_t *out,
                      size_t out_cap);

/*
 Derive the X25519 public key a peer needs in order to address this node.

 **A node that publishes no public key cannot be sent a direct message at
 all.** The sender refuses to fall back to channel encryption for a
 destination whose key it does not hold, and NAKs the packet locally — so
 the failure never reaches the air and presents as a dead link rather than
 as a missing key. `tests/captures/pki_dm_record.json` records that
 behaviour observed from the far side.

 `private_len` must be 32. The scalar is clamped internally per RFC 7748, so
 a caller may store the raw 32 bytes it drew: clamping is idempotent, and
 *not* clamping computes a different function rather than a weaker one.

 # This derives. It does not generate.

 Where the private key comes from, and where it is kept, is the caller's
 decision and deliberately outside this library. A portable `no_std` crate
 has no entropy source and no storage, and offering a `tm_keygen` that
 quietly used a weak one would put a security-critical choice behind an
 interface that cannot honour it. [`crate::TmUser::public_key`] is where the
 result belongs in a `tm_user_t`'s `public_key`; `backend::SecretKey::Slot`
 is the seam for a private key
 that never becomes addressable at all.
 */
int32_t tm_x25519_public(const uint8_t *private_key,
                         size_t private_len,
                         uint8_t *out,
                         size_t out_cap);

/*
 Build and encrypt a `NODEINFO_APP` frame announcing this node.

 Returns the frame length, or negative on error. The on-air payload for this
 port is a bare `User` — not a `NodeInfo` wrapping one — which is the shape
 the corpus shows and the shape a stock node parses.

 Broadcast it with `to = 0xFFFFFFFF`. When answering another node's request,
 address it to the asker instead and leave `want_response` clear, so that two
 nodes cannot ask each other in a loop.

 `relay_node` is stamped with the low byte of `from`, which is what an
 originating node does: `WIRE_REFERENCE.md` records the field as a one-byte
 truncation of the relaying node's number, corroborated on captured traffic
 for three separate nodes.
 */
int32_t tm_nodeinfo_encode(uint32_t from,
                           uint32_t to,
                           uint32_t id,
                           uint8_t hop_limit,
                           uint8_t channel_hash,
                           uint8_t want_response,
                           const struct tm_key_t *key,
                           const struct tm_user_t *user,
                           uint8_t *out,
                           size_t out_cap);

/*
 Agree the message key for one peer.

 Returns [`TM_E_SMALL_ORDER`] when the peer's public key drives the shared
 secret to zero. **That is never retryable and must never be treated as a
 transient failure** — a small-order key is chosen deliberately, and it makes
 the "shared" secret one the attacker knew in advance. It is a separate code
 from every other failure precisely so a caller cannot lump it in with a
 wrong length and retry.

 Agreement is the expensive half of this scheme — a scalar multiplication —
 while opening a frame is cheap. Keeping them apart lets a caller agree once
 per peer and keep the result, rather than paying for a ladder per frame.
 */
int32_t tm_pki_agree(const uint8_t *private_key,
                     size_t private_len,
                     const uint8_t *peer_public,
                     size_t peer_public_len,
                     struct tm_pki_key_t *out);

/*
 Is this frame a PKI direct message?

 Returns 1 if so, 0 if not, negative on a malformed input. **A channel hash
 of `0x00` is what marks one on the wire** — measured, not inferred — and a
 direct message is addressed rather than broadcast. A caller that guesses
 wrong runs the frame through the channel path, which does not fail: CTR
 decrypts anything into something.
 */
int32_t tm_is_pki(const uint8_t *frame, size_t frame_len);

/*
 Open a PKI direct message in place, leaving the plaintext borrowed from the
 caller's buffer.

 On success `payload` points into `frame` and `payload_len` is its length.

 **A failed tag is reported, never returned as data.** This is the property
 channel encryption does not have and the reason [`TM_E_UNAUTHENTIC`] exists
 as its own code: a forged message decrypts to *something*, and only the tag
 distinguishes it from a real one. On that error the buffer holds whatever
 the keystream produced and must be discarded.

 Layout, measured: `header(16) || ciphertext || tag(8) || extra_nonce(4)`,
 with the nonce built as `packet_id(LE) || extra_nonce || from(LE) || 0x00`.
 `extra_nonce` travels at the *end* of the payload, not with the header.
 */
int32_t tm_pki_decrypt(uint8_t *frame,
                       size_t frame_len,
                       const struct tm_pki_key_t *key,
                       const uint8_t **payload,
                       size_t *payload_len);

/*
 Build and seal a PKI direct message. Returns the frame length.

 `extra_nonce` must not repeat for a given `(from, id)` — it is nonce input,
 and a repeat under the same key reproduces a keystream. Draw it from the
 same source as any other nonce material.

 The channel hash is forced to `0x00`, which is what marks the frame as PKI
 on the wire; there is no channel key involved and no channel to name.
 */
int32_t tm_pki_encode(uint32_t from,
                      uint32_t to,
                      uint32_t id,
                      uint8_t hop_limit,
                      uint8_t want_ack,
                      const struct tm_pki_key_t *key,
                      uint32_t extra_nonce,
                      uint32_t portnum,
                      const uint8_t *payload,
                      size_t payload_len,
                      uint8_t *out,
                      size_t out_cap);

/*
 Read a decrypted payload as a `Data`.

 **A successful return is not an authenticity claim** on a channel-encrypted
 frame. CTR decrypts any bytes into some other bytes, so a wrong key yields
 plaintext that may still parse. Only a PKI frame's tag settles that; see
 [`tm_pki_decrypt`].
 */
int32_t tm_data_decode(const uint8_t *payload, size_t payload_len, struct tm_data_t *out);

/*
 Read a `NODEINFO_APP` payload as a `User`.

 The same `tm_user_t` the encoder takes, filled in the other direction, so a
 consumer has one description of a peer rather than two that can disagree.
 Every pointer borrows from `payload`.

 **This is how a node learns the public key it needs to address a peer.**
 Note what the wire permits: a `User` may legitimately carry no key at all,
 in which case `public_key_len` is 0 and that peer cannot be sent a direct
 message. That is a real state, not a decode failure.
 */
int32_t tm_user_decode(const uint8_t *payload, size_t payload_len, struct tm_user_t *out);

/*
 Decode the header of a received frame. No key, no state, no decision.

 Returns [`TM_E_SHORT`] for anything too short to hold a header, which is the
 only way this can fail: every 16-byte prefix is a well-formed header, because
 the layout has no reserved values to reject.
 */
int32_t tm_header_peek(const uint8_t *frame, size_t frame_len, struct tm_header_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TETHERMESH_H */
