//! Host-side tests.
//!
//! These run against the committed corpus in `tests/captures/` rather than
//! against hard-coded copies of it. That is deliberate: a vector table
//! transcribed into a test drifts from the capture it came from, and the
//! drift is invisible because both sides still agree with themselves.
//!
//! `tools/check_rust_rules.sh` exempts `*/tests/*` from the no-panic rules.
//! An assertion is a panic, and that is what an assertion is for.

use std::fs;
use std::path::PathBuf;

use tethermesh::backend::{Crypto as Backend, Error as BackendError, SecretKey, Software};
use tethermesh::channel::channel_hash;
use tethermesh::crypto::{
    Aes256,
    ccm_decrypt_in_place, ccm_encrypt_in_place, ctr_apply, expand_psk, nonce, Aes128, CcmError,
    Psk, CCM_TAG_LEN, DEFAULT_KEY,
};
use tethermesh::frame;
use tethermesh::header::{Header, HEADER_LEN};
use tethermesh::history::{PacketHistory, Seen};
use tethermesh::message::{ChannelSettings, Data, PortNum, User};
use tethermesh::packet_id::{NextId, PacketIdSource};
use tethermesh::protobuf::{Error as ProtoError, Reader, Value, Writer};
use tethermesh::sha256::{sha256, Sha256};
use tethermesh::x25519::{public_key, x25519};

fn captures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/captures")
}

/// Extract a quoted string field from a JSON object slice.
///
/// A deliberately small scanner rather than a JSON dependency: the corpus is
/// generated by us in a known shape, and `Cargo.toml` records that adding a
/// dependency has to clear a bar this does not need to clear.
fn json_str<'a>(obj: &'a str, key: &str) -> Option<&'a str> {
    let at = obj.find(&format!("\"{key}\""))?;
    let rest = obj.get(at.checked_add(key.len())?.checked_add(2)?..)?;
    let colon = rest.find(':')?;
    let after = rest.get(colon.checked_add(1)?..)?;
    let open = after.find('"')?;
    let body = after.get(open.checked_add(1)?..)?;
    let close = body.find('"')?;
    body.get(..close)
}

/// Extract an unsigned integer field from a JSON object slice.
fn json_u32(obj: &str, key: &str) -> Option<u32> {
    let at = obj.find(&format!("\"{key}\""))?;
    let rest = obj.get(at.checked_add(key.len())?.checked_add(2)?..)?;
    let colon = rest.find(':')?;
    let after = rest.get(colon.checked_add(1)?..)?;
    let digits: String = after
        .chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(char::is_ascii_digit)
        .collect();
    digits.parse().ok()
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    assert!(hex.len() % 2 == 0, "odd-length hex string: {hex:?}");
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("corpus contains non-hex in psk_hex"))
        .collect()
}

/// Split the corpus into the object slices that describe one vector each.
///
/// Vector objects are the ones carrying `psk_hex`; the provenance and
/// verified-properties blocks do not, so keying on it avoids having to
/// understand the surrounding structure.
fn vector_objects(doc: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut from = 0usize;
    while let Some(hit) = doc[from..].find("\"psk_hex\"") {
        let abs = from + hit;
        let start = doc[..abs].rfind('{').expect("psk_hex outside any object");
        let end = abs + doc[abs..].find('}').expect("unterminated object");
        out.push(&doc[start..=end]);
        from = end;
    }
    out
}

#[test]
fn channel_hash_matches_every_committed_vector() {
    let path = captures_dir().join("channel_hash.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let objects = vector_objects(&doc);
    assert!(
        objects.len() >= 6,
        "corpus shrank to {} vectors — a test that silently checks less is worse \
         than one that fails",
        objects.len()
    );

    let mut observed = 0usize;
    for obj in &objects {
        let name = json_str(obj, "name").expect("vector has no name");
        let psk_hex = json_str(obj, "psk_hex").expect("vector has no psk_hex");
        let expected = json_u32(obj, "expected_hash").expect("vector has no expected_hash");
        let kind = json_str(obj, "kind").unwrap_or("unspecified");

        let got = channel_hash(name.as_bytes(), &hex_to_bytes(psk_hex));
        assert_eq!(
            u32::from(got),
            expected,
            "channel_hash({name:?}, {psk_hex}) = 0x{got:02x}, corpus says 0x{expected:02x}"
        );
        if kind == "oracle-observed" {
            observed = observed.saturating_add(1);
        }
    }

    // The synthetic rows are computed from the same function under test, so
    // on their own they prove only self-consistency. The oracle-observed rows
    // are the ones that tie this implementation to the reference, and losing
    // them would gut the test without failing it.
    assert!(
        observed >= 2,
        "only {observed} oracle-observed vector(s) — the synthetic rows cannot \
         substitute, they are generated from this same function"
    );
}

/// Collect every `"hex": "..."` value in a document, in order.
fn all_hex(doc: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut from = 0usize;
    while let Some(hit) = doc[from..].find("\"hex\"") {
        let abs = from + hit;
        let rest = &doc[abs..];
        if let Some(v) = json_str(rest, "hex") {
            out.push(v);
        }
        from = abs + 5;
    }
    out
}

/// L3's gate, run against the reference implementation's own output.
///
/// Every message in the corpus was encoded by their encoder. Decoding it and
/// re-encoding it must reproduce the bytes exactly — not an equivalent
/// encoding, the same one. This is only an achievable requirement because
/// their encoder was measured to be canonical: minimal varints, fields in
/// ascending order. Had it been otherwise, byte-identity would have been
/// impossible and the gate itself would have needed rewriting.
#[test]
fn every_corpus_message_round_trips_bit_identically() {
    let path = captures_dir().join("fromradio_corpus.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let messages = all_hex(&doc);
    assert!(
        messages.len() >= 40,
        "corpus holds only {} messages — a gate that silently checks less is \
         not a gate",
        messages.len()
    );

    let mut total = 0usize;
    for (i, hex) in messages.iter().enumerate() {
        let original = hex_to_bytes(hex);

        let mut fields = Vec::new();
        let mut reader = Reader::new(&original);
        while let Some(field) = reader
            .next_field()
            .unwrap_or_else(|e| panic!("message {i}: decode failed: {e:?}\n  {hex}"))
        {
            fields.push(field);
        }
        assert!(!fields.is_empty(), "message {i} decoded to no fields");

        let mut out = vec![0u8; original.len()];
        let written = {
            let mut writer = Writer::new(&mut out);
            for field in &fields {
                writer
                    .field(field.number, &field.value)
                    .unwrap_or_else(|e| panic!("message {i}: encode failed: {e:?}"));
            }
            writer.len()
        };

        assert_eq!(
            written,
            original.len(),
            "message {i}: re-encoded to {written} bytes, original was {}",
            original.len()
        );
        assert_eq!(
            out, original,
            "message {i} did not round-trip bit-identically\n  original: {hex}\n  re-encoded: {}",
            out.iter().map(|b| format!("{b:02x}")).collect::<String>()
        );
        total = total.saturating_add(1);
    }
    assert_eq!(total, messages.len());
}

/// Round-trip `bytes`, then recurse into any length-delimited field that is
/// itself well-formed protobuf. Returns how many messages were checked.
///
/// Nesting has to be probed rather than known: at the wire layer a
/// length-delimited field may be a string, a byte blob or a nested message,
/// and nothing distinguishes them. Recursing wherever the bytes happen to
/// parse is sound for an identity check — if a string parses as a message and
/// re-encodes to itself, the assertion still holds — and it reaches real
/// nested messages, which is the point.
fn roundtrip_deep(bytes: &[u8], depth: usize, path: &str) -> usize {
    assert!(depth < 16, "{path}: nesting deeper than 16, refusing to recurse");

    let mut fields = Vec::new();
    let mut reader = Reader::new(bytes);
    loop {
        match reader.next_field() {
            Ok(Some(f)) => fields.push(f),
            Ok(None) => break,
            // Not a message at this level; nothing to check here.
            Err(_) => return 0,
        }
    }
    if fields.is_empty() {
        return 0;
    }

    let mut out = vec![0u8; bytes.len()];
    let written = {
        let mut writer = Writer::new(&mut out);
        for f in &fields {
            if writer.field(f.number, &f.value).is_err() {
                return 0;
            }
        }
        writer.len()
    };
    if written != bytes.len() {
        return 0;
    }
    assert_eq!(
        out, bytes,
        "{path}: nested message did not round-trip bit-identically"
    );

    let mut checked = 1usize;
    for f in &fields {
        if let Value::Len(inner) = f.value {
            if !inner.is_empty() {
                let child = format!("{path}/{}", f.number);
                checked = checked.saturating_add(roundtrip_deep(inner, depth + 1, &child));
            }
        }
    }
    checked
}

/// The gate again, but all the way down.
///
/// The property measured at capture time was top-level. This extends it to
/// every nested message the corpus contains, which is where a real encoder
/// bug would hide: a length prefix recomputed one byte differently is
/// invisible at the outer level because the outer length still matches.
#[test]
fn nested_messages_round_trip_bit_identically() {
    let path = captures_dir().join("fromradio_corpus.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let mut checked = 0usize;
    for (i, hex) in all_hex(&doc).iter().enumerate() {
        checked = checked.saturating_add(roundtrip_deep(&hex_to_bytes(hex), 0, &format!("msg{i}")));
    }
    // Strictly more than the 43 top-level messages, or the recursion never
    // reached anything and this test is checking the previous one again.
    assert!(
        checked > 43,
        "only {checked} messages checked — recursion found no nested messages, \
         so this adds nothing over the top-level gate (expected ~100 against \
         43 top-level)"
    );
}

/// `User` against real bytes the reference produced.
///
/// The corpus is `FromRadio`; field 4 is `node_info`, and `NodeInfo` field 2
/// is a `User`. Lifting it out gives a wrapper test tied to the reference
/// rather than to our own encoder's opinion of itself.
#[test]
fn user_wrapper_round_trips_reference_bytes() {
    let path = captures_dir().join("fromradio_corpus.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let mut seen = 0usize;
    for hex in all_hex(&doc) {
        let msg = hex_to_bytes(hex);
        let mut reader = Reader::new(&msg);
        while let Ok(Some(field)) = reader.next_field() {
            // FromRadio.node_info = 4
            let Value::Len(node_info) = field.value else { continue };
            if field.number != 4 {
                continue;
            }
            let mut inner = Reader::new(node_info);
            while let Ok(Some(nf)) = inner.next_field() {
                // NodeInfo.user = 2
                let Value::Len(user_bytes) = nf.value else { continue };
                if nf.number != 2 {
                    continue;
                }
                let user = User::decode(user_bytes).expect("reference User failed to decode");
                assert!(!user.id.is_empty(), "decoded User has no id");
                assert!(!user.long_name.is_empty(), "decoded User has no long_name");

                let mut out = vec![0u8; user_bytes.len()];
                let n = user.encode(&mut out).expect("re-encoding User failed");
                assert_eq!(
                    (n, &out[..n]),
                    (user_bytes.len(), user_bytes),
                    "User did not re-encode to the reference bytes"
                );
                seen = seen.saturating_add(1);
            }
        }
    }
    assert!(seen >= 1, "corpus contained no NodeInfo.user to test against");
}

#[test]
fn data_wrapper_round_trips() {
    let original = Data {
        portnum: PortNum::TEXT_MESSAGE_APP.0,
        payload: b"hello mesh",
        want_response: true,
        dest: 0x1234_5678,
        request_id: 0xdead_beef,
        bitfield: Some(1),
        ..Data::default()
    };
    let mut buf = [0u8; 128];
    let n = original.encode(&mut buf).expect("encode failed");
    let decoded = Data::decode(&buf[..n]).expect("decode failed");
    assert_eq!(decoded, original);

    let mut again = [0u8; 128];
    let m = decoded.encode(&mut again).expect("re-encode failed");
    assert_eq!(&buf[..n], &again[..m], "wrapper encoding is not stable");
}

/// Proto3 omits defaults, and so must we.
///
/// An explicit zero decodes to the same message but is a different byte
/// string, which would fail a comparison against reference output.
#[test]
fn wrapper_omits_default_valued_fields() {
    let mut buf = [0u8; 64];
    let n = Data::default().encode(&mut buf).expect("encode failed");
    assert_eq!(n, 0, "an all-default Data encoded to {n} bytes, expected 0");

    // `bitfield` is declared `optional`, so it has real presence: Some(0) is
    // not the same as absent, and must survive.
    let explicit_zero = Data { bitfield: Some(0), ..Data::default() };
    let n = explicit_zero.encode(&mut buf).expect("encode failed");
    assert!(n > 0, "an explicitly-set optional field was dropped as if absent");
    assert_eq!(Data::decode(&buf[..n]).expect("decode failed").bitfield, Some(0));
}

/// The documented limitation, asserted so it cannot change silently.
///
/// The wrapper drops fields it does not know. That is fine for reading a
/// frame and wrong for forwarding one, which is why the module documentation
/// says a relay path must not go through this layer. If this test ever fails,
/// the architecture note needs rewriting too.
#[test]
fn wrapper_drops_unknown_fields_and_the_primitive_layer_does_not() {
    // A Data with a plausible future field 15 that this build knows nothing of.
    let mut crafted = [0u8; 64];
    let n = {
        let mut w = Writer::new(&mut crafted);
        w.field(1, &Value::Varint(1)).unwrap();
        w.field(2, &Value::Len(b"hi")).unwrap();
        w.field(15, &Value::Varint(0x2a)).unwrap();
        w.len()
    };
    let original = &crafted[..n];

    let mut via_wrapper = [0u8; 64];
    let m = Data::decode(original)
        .expect("decode failed")
        .encode(&mut via_wrapper)
        .expect("encode failed");
    assert!(m < n, "expected the unknown field to be dropped, but nothing was lost");

    // The primitive layer keeps it, which is why relaying belongs there.
    // A floor rather than an exact count: `roundtrip_deep` recurses wherever
    // bytes happen to parse, and the two-byte payload "hi" is itself valid
    // protobuf, so it descends one level further than the crafted nesting.
    assert!(roundtrip_deep(original, 0, "crafted") >= 1);
}

/// The output buffer is caller-provided, so running out of room is an
/// ordinary outcome and must be reported rather than panicked on.
#[test]
fn encoding_into_a_short_buffer_reports_rather_than_panics() {
    let mut tiny = [0u8; 1];
    let mut writer = Writer::new(&mut tiny);
    let err = writer.field(1, &Value::Len(b"more than one byte")).unwrap_err();
    assert_eq!(err, ProtoError::BufferTooSmall);
}

/// Malformed input comes from the mesh, so every one of these must be an
/// error and none of them a panic. This is the negative twin of the
/// round-trip gate.
#[test]
fn malformed_input_errors_and_never_panics() {
    let cases: &[(&str, &[u8])] = &[
        ("truncated length-delimited", &[0x0a, 0x05, 0x01]),
        ("varint never terminates", &[0x08, 0x80, 0x80, 0x80]),
        ("varint longer than 64 bits", &[
            0x08, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x02,
        ]),
        ("group wire type 3", &[0x0b]),
        ("unassigned wire type 7", &[0x0f]),
        ("field number zero", &[0x00, 0x01]),
        ("truncated fixed32", &[0x0d, 0x01, 0x02]),
        ("truncated fixed64", &[0x09, 0x01, 0x02, 0x03]),
    ];
    for (name, bytes) in cases {
        let mut reader = Reader::new(bytes);
        // Drain: the error may surface on any field, not only the first.
        let errored = loop {
            match reader.next_field() {
                Ok(Some(_)) => continue,
                Ok(None) => break false,
                Err(_) => break true,
            }
        };
        assert!(
            errored,
            "{name}: accepted malformed input {bytes:02x?} instead of rejecting it"
        );
    }
}

#[test]
fn channel_hash_is_order_independent_within_each_input() {
    // XOR folding cannot distinguish orderings. Asserted rather than left
    // implicit, because it is a real property of the wire format: two
    // channel names that are anagrams share a hash, and anything that treats
    // a hash match as identification is wrong for reasons this test states.
    let psk = [0xAAu8, 0xBB, 0xCC];
    assert_eq!(channel_hash(b"abc", &psk), channel_hash(b"cba", &psk));
}

#[test]
fn empty_inputs_are_meaningful_not_invalid() {
    assert_eq!(channel_hash(b"", b""), 0);
    assert_eq!(channel_hash(b"\x5a", b""), 0x5a);
    assert_eq!(channel_hash(b"", b"\x5a"), 0x5a);
}


/// `ChannelSettings` against reference bytes, and the hash it feeds.
///
/// The corpus carries `FromRadio.channel` (10) holding a `Channel`, whose
/// `settings` (2) is a `ChannelSettings`. Re-encoding must be byte-identical,
/// and the primary channel's settings must produce the channel hash the
/// oracle was observed to use.
#[test]
fn channel_settings_round_trip_and_feed_the_verified_hash() {
    let doc = fs::read_to_string(captures_dir().join("fromradio_corpus.json")).unwrap();

    let mut checked = 0usize;
    let mut primary_hash = None;
    for hex in all_hex(&doc) {
        let msg = hex_to_bytes(hex);
        let mut reader = Reader::new(&msg);
        while let Ok(Some(field)) = reader.next_field() {
            let Value::Len(channel) = field.value else { continue };
            if field.number != 10 {
                continue;
            }
            let mut inner = Reader::new(channel);
            while let Ok(Some(cf)) = inner.next_field() {
                let Value::Len(settings_bytes) = cf.value else { continue };
                if cf.number != 2 {
                    continue;
                }
                let settings =
                    ChannelSettings::decode(settings_bytes).expect("settings failed to decode");

                let mut out = vec![0u8; settings_bytes.len()];
                let n = settings.encode(&mut out).expect("settings failed to encode");
                assert_eq!(
                    (n, &out[..n]),
                    (settings_bytes.len(), settings_bytes),
                    "ChannelSettings did not re-encode to the reference bytes"
                );
                checked = checked.saturating_add(1);

                // The default primary channel stores the PSK as the single
                // byte 0x01 — a short index, not a key. Expanded here to the
                // key the oracle was observed to use, which is the only form
                // the hash is defined over.
                if settings.psk == [0x01] {
                    let expanded =
                        hex_to_bytes("d4f1bb3a20290759f0bcffabcf4e6901");
                    let name = if settings.name.is_empty() {
                        b"LongFast".as_slice()
                    } else {
                        settings.name
                    };
                    primary_hash = Some(channel_hash(name, &expanded));
                }
            }
        }
    }
    assert!(checked >= 1, "corpus contained no ChannelSettings");
    assert_eq!(
        primary_hash,
        Some(0x08),
        "the primary channel's settings did not produce the hash the oracle used"
    );
}

/// Simulate a node that reboots at arbitrary, hostile moments.
///
/// Returns every identifier it managed to transmit. The rule modelled is the
/// one that matters: an identifier counts as used the moment it is handed
/// out, and a crash may occur between a durable write and the next write, or
/// part-way through a block, or immediately after resuming.
fn run_with_reboots(seed: u32, block: u32, reboots: &[usize]) -> Vec<u32> {
    let mut issued = Vec::new();
    // What survived the last crash. Only ever what was actually written.
    let mut durable = seed;

    for &packets_before_crash in reboots {
        let mut src = PacketIdSource::resume(durable, block);
        let mut sent = 0usize;
        while sent < packets_before_crash {
            match src.issue() {
                NextId::Ready(id) => {
                    issued.push(id);
                    sent += 1;
                }
                NextId::PersistFirst { high_water } => {
                    // The write lands, then is acknowledged. This is the only
                    // point at which `durable` may move.
                    durable = high_water;
                    src.persisted(high_water);
                }
                NextId::Exhausted => return issued,
            }
        }
        // Crash here: anything reserved-but-unissued is lost, and `durable`
        // keeps whatever was last written.
    }
    issued
}

/// PLAN's L2 requirement, stated there as: no `(packet_id, sender)` pair
/// repeats across a simulated reboot.
///
/// The sender is fixed for a given node, so the pair repeats exactly when the
/// identifier does. Under CTR that reissues a keystream, and the published
/// documentation says an attacker who deduces one plaintext can then forge
/// using the pair without the PSK. So this is a forgery test, not a
/// uniqueness nicety.
#[test]
fn packet_ids_never_repeat_across_reboots() {
    // Reboot after wildly varying numbers of packets, including 0 and values
    // that land mid-block and exactly on block boundaries.
    let schedules: &[&[usize]] = &[
        &[0, 1, 1, 1, 1],
        &[5, 5, 5, 5, 5],
        &[256, 1, 255, 257, 3],
        &[1000, 1, 1, 999],
        &[7, 0, 13, 0, 1, 512],
    ];
    for (n, schedule) in schedules.iter().enumerate() {
        for &block in &[1u32, 4, 256] {
            let ids = run_with_reboots(0, block, schedule);
            let unique: std::collections::HashSet<u32> = ids.iter().copied().collect();
            assert_eq!(
                unique.len(),
                ids.len(),
                "schedule {n} block {block}: {} identifiers issued, {} distinct — \
                 a repeat reissues a CTR keystream",
                ids.len(),
                unique.len()
            );
        }
    }
}

/// Identifiers are only issued below a mark that is already durable.
///
/// This is the property that makes the reboot test hold for reboots that
/// were not simulated, rather than only for the schedules listed above.
#[test]
fn no_id_is_issued_beyond_what_was_persisted() {
    let mut src = PacketIdSource::resume(0, 8);
    let mut durable: Option<u32> = None;
    for _ in 0..64 {
        match src.issue() {
            NextId::Ready(id) => {
                let mark = durable.expect("issued an identifier before anything was persisted");
                assert!(
                    id < mark,
                    "issued {id} but only {mark} is durable — an unclean restart would reissue it"
                );
            }
            NextId::PersistFirst { high_water } => {
                durable = Some(high_water);
                src.persisted(high_water);
            }
            NextId::Exhausted => break,
        }
    }
}

/// A stale or replayed confirmation must not move the mark backwards.
#[test]
fn a_stale_persist_confirmation_cannot_reopen_used_ids() {
    let mut src = PacketIdSource::resume(100, 16);
    let NextId::PersistFirst { high_water } = src.issue() else {
        panic!("expected a reservation first")
    };
    src.persisted(high_water);
    let NextId::Ready(first) = src.issue() else {
        panic!("expected an identifier")
    };

    src.persisted(0);
    src.persisted(high_water.saturating_sub(8));
    assert_eq!(src.reserved_until(), high_water, "the mark moved backwards");

    let NextId::Ready(second) = src.issue() else {
        panic!("expected an identifier")
    };
    assert!(second > first);
}

/// Exhaustion is reported, not wrapped.
///
/// Wrapping would reissue every identifier from the beginning, which is
/// precisely the failure this type exists to prevent.
#[test]
fn exhaustion_is_reported_rather_than_wrapping() {
    let mut src = PacketIdSource::resume(u32::MAX, 16);
    let mut saw_exhausted = false;
    for _ in 0..8 {
        match src.issue() {
            NextId::Exhausted => {
                saw_exhausted = true;
                break;
            }
            NextId::PersistFirst { high_water } => src.persisted(high_water),
            NextId::Ready(id) => assert_eq!(id, u32::MAX, "issued past the end of the space"),
        }
    }
    assert!(saw_exhausted, "ran off the end of the identifier space without saying so");
}

/// The domain red-list item: a duplicate `(from, id)` must not be forwarded
/// twice.
#[test]
fn a_repeated_packet_is_reported_as_duplicate() {
    let mut h: PacketHistory<8> = PacketHistory::new();
    assert_eq!(h.observe(0x7739_e49b, 0x59e2_815c), Seen::New);
    assert_eq!(h.observe(0x7739_e49b, 0x59e2_815c), Seen::Duplicate);
    assert_eq!(h.observe(0x7739_e49b, 0x59e2_815c), Seen::Duplicate);
    assert_eq!(h.len(), 1, "a duplicate consumed a slot");
}

/// Identifiers are unique per sender, not globally. Keying on the identifier
/// alone would silently suppress a stranger's traffic whenever a neighbour
/// happened to pick the same 32-bit number.
#[test]
fn the_same_id_from_a_different_sender_is_not_a_duplicate() {
    let mut h: PacketHistory<8> = PacketHistory::new();
    assert_eq!(h.observe(0xaaaa_aaaa, 42), Seen::New);
    assert_eq!(h.observe(0xbbbb_bbbb, 42), Seen::New);
    assert_eq!(h.observe(0xaaaa_aaaa, 43), Seen::New);
    assert_eq!(h.observe(0xaaaa_aaaa, 42), Seen::Duplicate);
    assert_eq!(h.observe(0xbbbb_bbbb, 42), Seen::Duplicate);
}

/// `(0, 0)` is a legitimate pair and must not read as an empty slot.
#[test]
fn zero_is_a_real_packet_not_an_empty_slot() {
    let mut h: PacketHistory<4> = PacketHistory::new();
    assert!(!h.contains(0, 0));
    assert_eq!(h.observe(0, 0), Seen::New);
    assert!(h.contains(0, 0));
    assert_eq!(h.observe(0, 0), Seen::Duplicate);
}

/// Memory is bounded, and eviction is oldest-first.
#[test]
fn the_oldest_entry_is_evicted_when_full() {
    const N: usize = 4;
    let mut h: PacketHistory<N> = PacketHistory::new();
    for id in 0..N as u32 {
        assert_eq!(h.observe(1, id), Seen::New);
    }
    assert_eq!(h.len(), N);
    assert_eq!(h.capacity(), N);

    // One more evicts the oldest, and only the oldest.
    assert_eq!(h.observe(1, 99), Seen::New);
    assert_eq!(h.len(), N, "history grew past its capacity");
    assert!(!h.contains(1, 0), "the oldest entry survived eviction");
    for id in 1..N as u32 {
        assert!(h.contains(1, id), "id {id} was evicted out of order");
    }
    assert!(h.contains(1, 99));
}

/// Far more traffic than capacity must neither grow nor wrap incorrectly.
#[test]
fn sustained_traffic_stays_bounded_and_remembers_the_most_recent() {
    const N: usize = 16;
    let mut h: PacketHistory<N> = PacketHistory::new();
    for id in 0..10_000u32 {
        assert_eq!(h.observe(7, id), Seen::New, "id {id} wrongly seen as a duplicate");
        assert!(h.len() <= N);
    }
    // The most recent N are remembered; anything older is not.
    for back in 1..=N as u32 {
        assert!(h.contains(7, 10_000 - back), "recent id was forgotten");
    }
    assert!(!h.contains(7, 10_000 - N as u32 - 1), "an evicted id came back");
}

/// A duplicate must not refresh its own entry, or one chattering node's
/// retransmissions would hold its slot while evicting everyone else's.
#[test]
fn repeats_do_not_keep_an_entry_alive() {
    const N: usize = 4;
    let mut h: PacketHistory<N> = PacketHistory::new();
    h.observe(1, 0);
    for _ in 0..50 {
        assert_eq!(h.observe(1, 0), Seen::Duplicate);
    }
    // Fill past capacity with other traffic; the repeated entry must age out
    // like anything else.
    for id in 1..=N as u32 {
        h.observe(2, id);
    }
    assert!(!h.contains(1, 0), "a repeated entry outlived its age");
}

/// The header codec against REAL captured frames.
///
/// These bytes came off the air from a stock Meshtastic node, so this is the
/// one test in the suite that can catch an endianness or bit-position error.
/// A round-trip against our own encoder cannot: it would agree with itself
/// perfectly while being wrong on the wire.
#[test]
fn header_decodes_and_re_encodes_real_captured_frames() {
    let doc = fs::read_to_string(captures_dir().join("on_air_frames.json"))
        .expect("cannot read on_air_frames.json");
    let raws: Vec<&str> = {
        let mut v = Vec::new();
        let mut from = 0usize;
        while let Some(hit) = doc[from..].find("\"raw_hex\"") {
            let abs = from + hit;
            if let Some(s) = json_str(&doc[abs..], "raw_hex") {
                v.push(s);
            }
            from = abs + 9;
        }
        v
    };
    assert!(raws.len() >= 3, "expected at least 3 captured frames, found {}", raws.len());

    for (i, hex) in raws.iter().enumerate() {
        let frame = hex_to_bytes(hex);
        assert!(frame.len() > HEADER_LEN, "frame {i} is shorter than a header");

        let h = Header::decode(&frame).expect("failed to decode a real frame");

        // Cross-checks against facts established by other means entirely.
        assert!(h.is_broadcast(), "frame {i}: captured frames were broadcasts");
        assert_eq!(h.from, 0x3369_e764, "frame {i}: sender does not match the transmitting board");
        assert_eq!(h.channel, 0x08, "frame {i}: channel hash should be LongFast's verified 0x08");
        assert_eq!(
            h.relay_node,
            (h.from & 0xFF) as u8,
            "frame {i}: relay_node must be the low byte of the sender"
        );
        assert_eq!(h.hop_limit, 3, "frame {i}: hop_limit was set to 3 when transmitting");
        assert_eq!(h.hop_start, 3, "frame {i}: hop_start should match the original hop_limit");
        assert!(!h.want_ack);
        assert!(!h.via_mqtt);
        assert_eq!(h.next_hop, 0);

        // And byte-exact back out again.
        assert_eq!(
            h.encode()[..],
            frame[..HEADER_LEN],
            "frame {i} did not re-encode to the captured bytes"
        );
    }
}

/// Endianness is the error this catches, so state it as its own assertion.
#[test]
fn multibyte_header_fields_are_little_endian() {
    let frame = hex_to_bytes("ffffffff64e76933432397ea63080064");
    let h = Header::decode(&frame).unwrap();
    assert_eq!(h.from, 0x3369_e764, "from is little-endian on the wire");
    assert_eq!(h.id, 0xea97_2343, "id is little-endian on the wire");
    // Big-endian would have produced these, and they are what a plausible
    // wrong implementation returns.
    assert_ne!(h.from, 0x64e7_6933);
    assert_ne!(h.id, 0x4323_97ea);
}

#[test]
fn relaying_spends_one_hop_and_preserves_the_originators_channel() {
    let frame = hex_to_bytes("ffffffff64e76933432397ea63080064");
    let h = Header::decode(&frame).unwrap();

    let relayed = h.relayed_by(0x336a_0d28).expect("3 hops left, should relay");
    assert_eq!(relayed.hop_limit, 2, "one hop should have been spent");
    assert_eq!(relayed.hop_start, 3, "hop_start must not change on relay");
    assert_eq!(relayed.relay_node, 0x28, "relay_node becomes OUR low byte");
    assert_eq!(
        relayed.channel, 0x08,
        "the ORIGINATOR's channel hash must survive relay — observed behaviour, \
         and what carriage of foreign traffic depends on"
    );
    assert_eq!(relayed.from, h.from, "from must not become the relay");
    assert_eq!(relayed.id, h.id);
}

#[test]
fn a_spent_packet_is_not_relayed() {
    let mut h = Header::decode(&hex_to_bytes("ffffffff64e76933432397ea63080064")).unwrap();
    h.hop_limit = 0;
    assert!(h.relayed_by(0x336a_0d28).is_none(), "hop_limit 0 must not be forwarded");
}

#[test]
fn a_short_frame_is_rejected_rather_than_read_past() {
    for n in 0..HEADER_LEN {
        assert!(Header::decode(&vec![0u8; n]).is_none(), "accepted a {n}-byte header");
    }
    assert!(Header::decode(&[0u8; HEADER_LEN]).is_some());
}

/// FIPS-197 Appendix C.1 — the published AES-128 known-answer vector.
///
/// Checked before anything else: if the block cipher is wrong, every
/// downstream test is testing the wrong thing, and a CTR test would still
/// "pass" against our own broken keystream.
#[test]
fn aes128_matches_the_fips197_vector() {
    let key = hex_to_bytes("000102030405060708090a0b0c0d0e0f");
    let mut block = [0u8; 16];
    block.copy_from_slice(&hex_to_bytes("00112233445566778899aabbccddeeff"));

    let mut k = [0u8; 16];
    k.copy_from_slice(&key);
    Aes128::new(&k).encrypt_block(&mut block);

    assert_eq!(
        block.iter().map(|b| format!("{b:02x}")).collect::<String>(),
        "69c4e0d86a7b0430d8cdb78070b4c55a"
    );
}

/// The nonce construction, against frames captured off the air.
///
/// The plaintext is known because we transmitted it, so this is a direct
/// check rather than a plausibility argument: wrong nonce, wrong byte order
/// or wrong counter semantics all produce garbage rather than the text.
#[test]
fn captured_frames_decrypt_to_the_text_that_was_transmitted() {
    let doc = fs::read_to_string(captures_dir().join("on_air_frames.json")).unwrap();

    let mut raws = Vec::new();
    let mut from = 0usize;
    while let Some(hit) = doc[from..].find("\"raw_hex\"") {
        let abs = from + hit;
        if let Some(s) = json_str(&doc[abs..], "raw_hex") {
            raws.push(s.to_string());
        }
        from = abs + 9;
    }
    assert!(raws.len() >= 3);

    let Psk::Aes128(key) = expand_psk(&[0x01]).expect("short PSK #1 must expand") else {
        panic!("the default channel key is AES-128")
    };

    for (i, hex) in raws.iter().enumerate() {
        let frame = hex_to_bytes(hex);
        let h = Header::decode(&frame).unwrap();
        let mut body = frame[HEADER_LEN..].to_vec();

        ctr_apply(&key, &nonce(h.id, h.from, 0), &mut body);

        let text = format!("sniff-probe-{i}");
        let found = String::from_utf8_lossy(&body).contains(&text);
        assert!(
            found,
            "frame {i} did not decrypt to {text:?}; got {}",
            body.iter().map(|b| format!("{b:02x}")).collect::<String>()
        );

        // And it must be a well-formed Data message, not merely contain the text.
        let d = Data::decode(&body).expect("plaintext should parse as Data");
        assert_eq!(d.portnum, PortNum::TEXT_MESSAGE_APP.0);
        assert_eq!(d.payload, text.as_bytes());
    }
}

/// CTR is its own inverse, and must cross an AES block boundary correctly.
#[test]
fn ctr_is_symmetric_across_block_boundaries() {
    let key = [0x42u8; 16];
    let n = nonce(0xdead_beef, 0x1234_5678, 0);
    for len in [0usize, 1, 15, 16, 17, 31, 32, 33, 200] {
        let original: Vec<u8> = (0..len).map(|i| (i as u8).wrapping_mul(31)).collect();
        let mut buf = original.clone();
        ctr_apply(&key, &n, &mut buf);
        if len > 0 {
            assert_ne!(buf, original, "len {len}: ciphertext equals plaintext");
        }
        ctr_apply(&key, &n, &mut buf);
        assert_eq!(buf, original, "len {len}: round trip failed");
    }
}

/// A stored PSK is an index, not a key. Feeding the stored bytes straight to
/// AES computes a different key for the most common channel on the network.
#[test]
fn short_psk_indices_expand_to_the_documented_keys() {
    assert_eq!(expand_psk(&[]), Some(Psk::None));
    assert_eq!(expand_psk(&[0x00]), Some(Psk::None));

    let Psk::Aes128(k1) = expand_psk(&[0x01]).unwrap() else { panic!() };
    assert_eq!(k1, DEFAULT_KEY, "index 1 is the default key unchanged");

    // 2..=10 add n-1 to the LAST byte.
    let Psk::Aes128(k2) = expand_psk(&[0x02]).unwrap() else { panic!() };
    assert_eq!(k2[15], DEFAULT_KEY[15].wrapping_add(1));
    assert_eq!(k2[..15], DEFAULT_KEY[..15]);

    let Psk::Aes128(k10) = expand_psk(&[0x0a]).unwrap() else { panic!() };
    assert_eq!(k10[15], DEFAULT_KEY[15].wrapping_add(9));

    assert_eq!(expand_psk(&[0x0b]), None, "index 11 is not defined");
    assert!(matches!(expand_psk(&[0u8; 16]), Some(Psk::Aes128(_))));
    assert!(matches!(expand_psk(&[0u8; 32]), Some(Psk::Aes256(_))));
    assert_eq!(expand_psk(&[0u8; 7]), None, "undefined length must be rejected");
}

/// End to end against real traffic: parse a captured frame, and rebuild it.
///
/// This is the whole of L2 in one assertion. If our encoder reproduces the
/// exact bytes a stock node put on the air, then the header layout, the
/// endianness, the flag packing, the PSK expansion, the nonce construction
/// and the CTR counter semantics are all simultaneously right.
#[test]
fn a_captured_frame_survives_decode_then_encode_byte_for_byte() {
    let doc = fs::read_to_string(captures_dir().join("on_air_frames.json")).unwrap();
    let mut raws = Vec::new();
    let mut from = 0usize;
    while let Some(hit) = doc[from..].find("\"raw_hex\"") {
        let abs = from + hit;
        if let Some(s) = json_str(&doc[abs..], "raw_hex") {
            raws.push(s.to_string());
        }
        from = abs + 9;
    }
    assert!(raws.len() >= 3);

    let Psk::Aes128(key) = expand_psk(&[0x01]).unwrap() else { panic!() };

    for (i, hex) in raws.iter().enumerate() {
        let original = hex_to_bytes(hex);

        let mut work = original.clone();
        let (hdr, plain) = frame::decode_in_place(&mut work, &key, 0).expect("decode failed");
        let plain = plain.to_vec();

        assert_eq!(
            Data::decode(&plain).unwrap().payload,
            format!("sniff-probe-{i}").as_bytes()
        );

        let mut rebuilt = vec![0u8; frame::MAX_FRAME];
        let n = frame::encode(&hdr, &plain, &key, 0, &mut rebuilt).expect("encode failed");
        assert_eq!(
            &rebuilt[..n],
            &original[..],
            "frame {i} did not rebuild to the bytes that were on the air"
        );
    }
}

/// A relay reads the header without a key, because it may not have one.
#[test]
fn a_relay_reads_the_header_without_any_key() {
    let doc = fs::read_to_string(captures_dir().join("on_air_frames.json")).unwrap();
    let hex = json_str(&doc[doc.find("\"raw_hex\"").unwrap()..], "raw_hex").unwrap();
    let f = hex_to_bytes(hex);

    let hdr = frame::peek_header(&f).expect("a relay must be able to read any header");
    assert_eq!(hdr.channel, 0x08);
    assert_eq!(hdr.hop_limit, 3);

    // The ciphertext is untouched by peeking — a relay forwards it verbatim.
    assert_eq!(frame::payload(&f).unwrap(), &f[HEADER_LEN..]);

    let relayed = hdr.relayed_by(0x336a_0d28).unwrap();
    let mut out = vec![0u8; frame::MAX_FRAME];
    let n = frame::encode(&relayed, frame::payload(&f).unwrap(), &key_none(), 0, &mut out);
    // Encoding with the wrong key would re-encrypt; a real relay re-emits the
    // ciphertext as-is. Assert only that the header half is right.
    assert!(n.is_ok());
    assert_eq!(&out[..HEADER_LEN], &relayed.encode()[..]);
}

fn key_none() -> [u8; 16] { [0u8; 16] }

#[test]
fn frame_size_limits_are_enforced_not_assumed() {
    let key = key_none();
    let h = Header::default();
    let mut out = vec![0u8; frame::MAX_FRAME];

    assert_eq!(frame::encode(&h, &[0u8; 233], &key, 0, &mut out), Ok(frame::MAX_FRAME));
    assert_eq!(
        frame::encode(&h, &[0u8; 234], &key, 0, &mut out),
        Err(frame::Error::PayloadTooLong),
        "233 is DATA_PAYLOAD_LEN; 237 is the figure usually quoted and is wrong"
    );

    let mut tiny = [0u8; 8];
    assert_eq!(
        frame::encode(&h, &[1, 2, 3], &key, 0, &mut tiny),
        Err(frame::Error::BufferTooSmall)
    );

    for n in 0..HEADER_LEN {
        let mut short = vec![0u8; n];
        assert_eq!(frame::decode_in_place(&mut short, &key, 0).map(|_| ()), Err(frame::Error::TooShort));
        assert_eq!(frame::peek_header(&short), Err(frame::Error::TooShort));
    }
}

/// Emit a frame built entirely by OUR encoder, for the bench to transmit.
///
/// Run with `--nocapture`; the bench harness greps the `CONFORMANCE_FRAME`
/// line and puts those exact bytes on the air. This is the direction
/// `TESTING.md` says fails in the field — a decoder that is merely lenient
/// passes every inbound test while emitting frames nobody accepts — so the
/// bytes must come from the real encoder rather than from a script that
/// happens to agree with it.
#[test]
fn emit_conformance_frame_for_the_bench() {
    // A node number that is obviously ours, so anything that receives it
    // cannot be confused with real bench traffic.
    const FROM: u32 = 0x7e57_0001;
    const ID: u32 = 0x0bad_c0de;
    const TEXT: &[u8] = b"tethermesh-conformance-1";

    let Psk::Aes128(key) = expand_psk(&[0x01]).unwrap() else { panic!() };

    let data = Data {
        portnum: PortNum::TEXT_MESSAGE_APP.0,
        payload: TEXT,
        ..Data::default()
    };
    let mut payload = [0u8; 64];
    let plen = data.encode(&mut payload).expect("Data encode failed");

    let header = Header {
        to: 0xFFFF_FFFF,
        from: FROM,
        id: ID,
        hop_limit: 3,
        hop_start: 3,
        channel: channel_hash(b"LongFast", &key),
        next_hop: 0,
        relay_node: (FROM & 0xFF) as u8,
        ..Header::default()
    };
    assert_eq!(header.channel, 0x08, "must land on the default channel to be heard");

    let mut frame_buf = [0u8; frame::MAX_FRAME];
    let n = frame::encode(&header, &payload[..plen], &key, 0, &mut frame_buf)
        .expect("frame encode failed");

    println!(
        "CONFORMANCE_FRAME {}",
        frame_buf[..n].iter().map(|b| format!("{b:02x}")).collect::<String>()
    );
    println!("CONFORMANCE_TEXT {}", core::str::from_utf8(TEXT).unwrap());
}

/// Emit a NodeInfo frame, so a stock node can be asked whether it lists us.
///
/// The on-air payload for `NODEINFO_APP` is a bare `User`, which exercises the
/// wrapper that was verified against reference bytes earlier — this time in
/// the emitting direction, where being wrong is not forgiven.
#[test]
fn emit_nodeinfo_frame_for_the_bench() {
    const FROM: u32 = 0x7e57_0001;
    // Overridable: a repeated (from, id) is dropped by their duplicate
    // suppression, so a resend with a stale id is indistinguishable from a
    // frame that never arrived. That has now cost two debugging cycles.
    let id: u32 = std::env::var("NI_ID").ok()
        .and_then(|v| u32::from_str_radix(v.trim_start_matches("0x"), 16).ok())
        .unwrap_or(0x0bad_c0df);

    let Psk::Aes128(key) = expand_psk(&[0x01]).unwrap() else { panic!() };

    // Our X25519 public key, supplied by the bench. Publishing it is what
    // lets a stock node choose the PKI path when it addresses us — the
    // scheme cannot be observed until something uses it.
    let pk_hex = std::env::var("TM_PUBKEY").unwrap_or_default();
    let pk: Vec<u8> = (0..pk_hex.len() / 2)
        .map(|i| u8::from_str_radix(&pk_hex[i * 2..i * 2 + 2], 16).unwrap_or(0))
        .collect();

    let user = User {
        id: b"!7e570001",
        long_name: b"tethermesh",
        short_name: b"tm",
        public_key: &pk,
        // Deprecated since 2.1.x and still emitted by 2.7.26 — matching what
        // a stock node puts on the wire rather than what the schema implies.
        macaddr: &[0, 0, 0, 0, 0, 0],
        hw_model: 43,
        ..User::default()
    };
    let mut ubuf = [0u8; 128];
    let ulen = user.encode(&mut ubuf).expect("User encode failed");

    let data = Data {
        portnum: PortNum::NODEINFO_APP.0,
        payload: &ubuf[..ulen],
        want_response: false,
        ..Data::default()
    };
    let mut payload = [0u8; 200];
    let plen = data.encode(&mut payload).expect("Data encode failed");

    let header = Header {
        to: 0xFFFF_FFFF,
        from: FROM,
        id,
        hop_limit: 3,
        hop_start: 3,
        channel: channel_hash(b"LongFast", &key),
        relay_node: (FROM & 0xFF) as u8,
        ..Header::default()
    };
    let mut fb = [0u8; frame::MAX_FRAME];
    let n = frame::encode(&header, &payload[..plen], &key, 0, &mut fb).expect("frame encode failed");
    println!(
        "NODEINFO_FRAME {}",
        fb[..n].iter().map(|b| format!("{b:02x}")).collect::<String>()
    );
}

/// Emit a traceroute request addressed to the stock node.
///
/// `TRACEROUTE_APP` carries a `RouteDiscovery`, empty on the way out — the
/// firmware appends each hop. Addressed rather than broadcast, and with
/// `want_response`, because the interesting part is whether they answer.
#[test]
fn emit_traceroute_frame_for_the_bench() {
    const FROM: u32 = 0x7e57_0001;
    const TO: u32 = 0x3369_e764;          // the stock Heltec on the bench
    // Overridable, because a repeated (from, id) is dropped by the receiver's
    // duplicate suppression — the same behaviour history.rs implements, seen
    // from the far side. A rerun with a stale id looks exactly like a frame
    // that never arrived.
    let id: u32 = std::env::var("TR_ID").ok()
        .and_then(|v| u32::from_str_radix(v.trim_start_matches("0x"), 16).ok())
        .unwrap_or(0x0bad_c0e0);

    let Psk::Aes128(key) = expand_psk(&[0x01]).unwrap() else { panic!() };

    let data = Data {
        portnum: 70,                       // TRACEROUTE_APP
        payload: &[],                      // empty RouteDiscovery
        want_response: true,
        ..Data::default()
    };
    let mut payload = [0u8; 64];
    let plen = data.encode(&mut payload).expect("Data encode failed");

    let header = Header {
        to: TO,
        from: FROM,
        id,
        hop_limit: 3,
        hop_start: 3,
        want_ack: false,
        channel: channel_hash(b"LongFast", &key),
        relay_node: (FROM & 0xFF) as u8,
        ..Header::default()
    };
    let mut fb = [0u8; frame::MAX_FRAME];
    let n = frame::encode(&header, &payload[..plen], &key, 0, &mut fb).expect("frame encode failed");
    println!(
        "TRACEROUTE_FRAME {}",
        fb[..n].iter().map(|b| format!("{b:02x}")).collect::<String>()
    );
}

/// FIPS 180-4 / RFC 6234 published SHA-256 vectors.
#[test]
fn sha256_matches_published_vectors() {
    let cases: &[(&[u8], &str)] = &[
        (b"", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
        (b"abc", "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"),
        (b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
         "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"),
    ];
    for (input, want) in cases {
        let got = sha256(input).iter().map(|b| format!("{b:02x}")).collect::<String>();
        assert_eq!(&got, want, "sha256({:?})", core::str::from_utf8(input).unwrap_or("<bytes>"));
    }
    // A multi-block input, and the streaming path split at an awkward point.
    let long = vec![b'a'; 1000];
    let one_shot = sha256(&long);
    let mut h = Sha256::new();
    h.update(&long[..7]);
    h.update(&long[7..129]);
    h.update(&long[129..]);
    assert_eq!(h.finalize(), one_shot, "streaming and one-shot must agree");
}

/// The KDF, against the key a real stock node derived.
///
/// The firmware printed the first bytes of its shared key while sending us a
/// direct message. Reproducing them from the raw X25519 secret is what pinned
/// the KDF as plain SHA-256 rather than anything with a salt or a label.
#[test]
fn the_pki_kdf_reproduces_a_real_nodes_derived_key() {
    let shared = hex_to_bytes("b82315ffc2c374aba1ee1b290a7d4823a1837049920f9821b34a4dfd0a8f3d60");
    let derived = sha256(&shared);
    let prefix = derived[..8].iter().map(|b| format!("{b:02x}")).collect::<String>();
    assert_eq!(
        prefix, "d885d224e6cc3de0",
        "must match the shared_key prefix the firmware logged"
    );
}

/// AES-256-CCM against a real PKI direct message captured off the air.
///
/// Everything here came from the bench: the frame from our receiver, the
/// shared secret from an X25519 exchange whose both halves we hold. If this
/// decrypts, the KDF, the key size, the nonce layout, the tag length and the
/// payload framing are all simultaneously right.
#[test]
fn a_captured_pki_direct_message_decrypts() {
    let doc = fs::read_to_string(captures_dir().join("pki_dm_record.json")).unwrap();
    let frame_hex = json_str(&doc[doc.find("\"frame_hex\"").unwrap()..], "frame_hex").unwrap();
    let frame = hex_to_bytes(frame_hex);

    let hdr = Header::decode(&frame).expect("header");
    assert_eq!(hdr.channel, 0x00, "a PKI packet is marked by channel byte 0x00");
    assert!(!hdr.is_broadcast(), "a direct message is addressed");

    // SHA-256 over the raw X25519 shared secret — our own hash, our own KDF.
    let shared = hex_to_bytes("b82315ffc2c374aba1ee1b290a7d4823a1837049920f9821b34a4dfd0a8f3d60");
    let key = sha256(&shared);

    let payload = &frame[HEADER_LEN..];
    let extra = &payload[payload.len() - 4..];
    let body = &payload[..payload.len() - 4];

    // nonce = packet_id(LE) || extra_nonce || from(LE) || 0x00
    let mut nonce = [0u8; 13];
    nonce[..4].copy_from_slice(&hdr.id.to_le_bytes());
    nonce[4..8].copy_from_slice(extra);
    nonce[8..12].copy_from_slice(&hdr.from.to_le_bytes());
    assert_eq!(
        nonce.iter().map(|b| format!("{b:02x}")).collect::<String>(),
        "9af44fc02df4515864e7693300",
        "must match the nonce the firmware logged"
    );

    let mut work = body.to_vec();
    let n = ccm_decrypt_in_place(&key, &nonce, &mut work, CCM_TAG_LEN)
        .expect("the tag must verify against a genuine message");

    let d = Data::decode(&work[..n]).expect("plaintext should parse as Data");
    assert_eq!(d.portnum, PortNum::TEXT_MESSAGE_APP.0);
    assert_eq!(d.payload, b"pki-probe-B");
}

/// A forged or corrupted direct message must be rejected, not decrypted.
///
/// This is the property channel encryption does not have: CTR will decrypt
/// anything into something, and only CCM's tag distinguishes a real message
/// from an attacker's.
#[test]
fn a_tampered_pki_message_fails_authentication() {
    let doc = fs::read_to_string(captures_dir().join("pki_dm_record.json")).unwrap();
    let frame_hex = json_str(&doc[doc.find("\"frame_hex\"").unwrap()..], "frame_hex").unwrap();
    let frame = hex_to_bytes(frame_hex);
    let hdr = Header::decode(&frame).unwrap();
    let shared = hex_to_bytes("b82315ffc2c374aba1ee1b290a7d4823a1837049920f9821b34a4dfd0a8f3d60");
    let key = sha256(&shared);
    let payload = &frame[HEADER_LEN..];
    let extra = &payload[payload.len() - 4..];
    let body = &payload[..payload.len() - 4];
    let mut nonce = [0u8; 13];
    nonce[..4].copy_from_slice(&hdr.id.to_le_bytes());
    nonce[4..8].copy_from_slice(extra);
    nonce[8..12].copy_from_slice(&hdr.from.to_le_bytes());

    for flip in [0usize, 5, 16, 20] {
        let mut work = body.to_vec();
        work[flip] ^= 0x01;
        assert_eq!(
            ccm_decrypt_in_place(&key, &nonce, &mut work, CCM_TAG_LEN),
            Err(CcmError::Unauthentic),
            "flipping byte {flip} must fail the tag"
        );
    }
    // A wrong key must also fail, not merely produce garbage.
    let mut work = body.to_vec();
    assert_eq!(
        ccm_decrypt_in_place(&[0u8; 32], &nonce, &mut work, CCM_TAG_LEN),
        Err(CcmError::Unauthentic)
    );
}

#[test]
fn ccm_round_trips_and_rejects_short_buffers() {
    let key = sha256(b"a shared secret");
    let nonce = [7u8; 13];
    for len in [0usize, 1, 15, 16, 17, 100] {
        let mut buf = vec![0u8; len + CCM_TAG_LEN];
        for (i, b) in buf.iter_mut().take(len).enumerate() {
            *b = (i as u8).wrapping_mul(7);
        }
        let original = buf[..len].to_vec();
        let total = ccm_encrypt_in_place(&key, &nonce, &mut buf, len, CCM_TAG_LEN).unwrap();
        assert_eq!(total, len + CCM_TAG_LEN);
        if len > 0 {
            assert_ne!(&buf[..len], &original[..], "len {len}: ciphertext equals plaintext");
        }
        let n = ccm_decrypt_in_place(&key, &nonce, &mut buf[..total], CCM_TAG_LEN).unwrap();
        assert_eq!(n, len);
        assert_eq!(&buf[..len], &original[..], "len {len}: round trip failed");
    }
    let mut tiny = [0u8; 4];
    assert_eq!(
        ccm_decrypt_in_place(&key, &nonce, &mut tiny, CCM_TAG_LEN),
        Err(CcmError::TooShort)
    );
    let mut buf = [0u8; 32];
    assert_eq!(
        ccm_decrypt_in_place(&key, &[0u8; 12], &mut buf, CCM_TAG_LEN),
        Err(CcmError::BadNonce)
    );
}

/// RFC 7748 section 5.2 published X25519 vectors.
#[test]
fn x25519_matches_rfc7748_vectors() {
    let cases = [
        ("a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4",
         "e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c",
         "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552"),
        ("4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d",
         "e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493",
         "95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957"),
    ];
    for (k, u, want) in cases {
        let mut ks = [0u8; 32];
        ks.copy_from_slice(&hex_to_bytes(k));
        let mut us = [0u8; 32];
        us.copy_from_slice(&hex_to_bytes(u));
        let got = x25519(&ks, &us).expect("non-zero result");
        assert_eq!(got.iter().map(|b| format!("{b:02x}")).collect::<String>(), want);
    }
}

/// The base point, and agreement in both directions.
#[test]
fn x25519_public_keys_agree_both_ways() {
    let a = hex_to_bytes("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a");
    let b = hex_to_bytes("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb");
    let (mut ka, mut kb) = ([0u8; 32], [0u8; 32]);
    ka.copy_from_slice(&a);
    kb.copy_from_slice(&b);

    // RFC 7748 section 6.1 publishes both public keys for these scalars.
    assert_eq!(
        public_key(&ka).iter().map(|x| format!("{x:02x}")).collect::<String>(),
        "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a"
    );
    assert_eq!(
        public_key(&kb).iter().map(|x| format!("{x:02x}")).collect::<String>(),
        "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f"
    );

    let s1 = x25519(&ka, &public_key(&kb)).unwrap();
    let s2 = x25519(&kb, &public_key(&ka)).unwrap();
    assert_eq!(s1, s2, "both parties must derive the same secret");
    assert_eq!(
        s1.iter().map(|x| format!("{x:02x}")).collect::<String>(),
        "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742"
    );
}

/// The exchange that actually happened on the bench.
///
/// A stock node encrypted a direct message to a public key we published, and
/// this reproduces the secret behind it — closing the loop from key agreement
/// through KDF to the decrypted text.
#[test]
fn x25519_reproduces_the_bench_exchange_and_decrypts_the_message() {
    let mut our_priv = [0u8; 32];
    our_priv.copy_from_slice(&hex_to_bytes(
        "2085445b15f80cffb7cdd4f254d3e27826c867708b93d13960d6c09e1404be74",
    ));
    let mut their_pub = [0u8; 32];
    their_pub.copy_from_slice(&hex_to_bytes(
        "f2b087c1c61c900292a54c6237ddc5e0e168d07b3dd684892fe2589495b1f574",
    ));

    // Our published public key must be what we told them it was.
    assert_eq!(
        public_key(&our_priv).iter().map(|b| format!("{b:02x}")).collect::<String>(),
        "f771ce1cc233e1e28bf8a4ad4fd8acd1ff263ef59e238d3f5f6a73372b7a9a7f"
    );

    let shared = x25519(&our_priv, &their_pub).expect("non-zero");
    assert_eq!(
        shared.iter().map(|b| format!("{b:02x}")).collect::<String>(),
        "b82315ffc2c374aba1ee1b290a7d4823a1837049920f9821b34a4dfd0a8f3d60",
        "must match the secret computed from their private key"
    );

    // ...and the whole chain, ending in the text they sent.
    let key = sha256(&shared);
    let doc = fs::read_to_string(captures_dir().join("pki_dm_record.json")).unwrap();
    let frame = hex_to_bytes(json_str(&doc[doc.find("\"frame_hex\"").unwrap()..], "frame_hex").unwrap());
    let hdr = Header::decode(&frame).unwrap();
    let payload = &frame[HEADER_LEN..];
    let mut nonce = [0u8; 13];
    nonce[..4].copy_from_slice(&hdr.id.to_le_bytes());
    nonce[4..8].copy_from_slice(&payload[payload.len() - 4..]);
    nonce[8..12].copy_from_slice(&hdr.from.to_le_bytes());
    let mut work = payload[..payload.len() - 4].to_vec();
    let n = ccm_decrypt_in_place(&key, &nonce, &mut work, CCM_TAG_LEN).unwrap();
    assert_eq!(Data::decode(&work[..n]).unwrap().payload, b"pki-probe-B");
}

/// A small-order public key drives the output to zero whatever the private
/// key is, so accepting it agrees a secret an attacker already knows.
///
/// **All seven canonical values, not a sample.** This test previously carried
/// three of them, which the 2026-08-16 audit flagged as constraining less than
/// the name implies: the two order-8 points are the interesting ones and only
/// one was present, and the non-canonical encodings above `p` were absent
/// entirely — those are exactly the inputs where a sloppy reduction turns a
/// rejection into an acceptance. This is the list libsodium blacklists.
///
/// It is also checked against `x25519-dalek` rather than only against itself.
/// A hand-maintained list of "bad points" is worth little if the reason each
/// one is bad is our own belief; asserting the oracle drives them to zero too
/// is what makes this a check rather than a restatement.
#[test]
fn small_order_public_keys_are_rejected() {
    let small_order = [
        // u = 0 and u = 1.
        ("0000000000000000000000000000000000000000000000000000000000000000", "zero"),
        ("0100000000000000000000000000000000000000000000000000000000000000", "one"),
        // The two points of order 8 — the pair that actually matters.
        ("e0eb7a7c3b41b8ae1656e3faf19fc46ada098deb9c32b1fd866205165f49b800", "order 8 (a)"),
        ("5f9c95bca3508c24b1d0b1559c83ef5b04445cc4581c8e86d8224eddd09f1157", "order 8 (b)"),
        // Non-canonical encodings: p-1, p and p+1 reduce to -1, 0 and 1.
        // A reduction that stops short accepts these, which is precisely the
        // bug class the fe_sub defect belonged to.
        ("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", "p-1"),
        ("edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", "p"),
        ("eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", "p+1"),
    ];

    // Several private keys, because the whole point of a small-order point is
    // that it forces the output regardless of the scalar. One key could pass
    // by coincidence; these cannot.
    for priv_key in [[0x11u8; 32], [0xFFu8; 32], [0x01u8; 32], [0xA5u8; 32]] {
        for (bad, label) in small_order {
            let mut p = [0u8; 32];
            p.copy_from_slice(&hex_to_bytes(bad));

            assert_eq!(
                x25519(&priv_key, &p),
                None,
                "small-order point ({label}) {bad} must be rejected"
            );

            // ...and the oracle agrees it is degenerate, so the list is not
            // just an article of faith carried forward from somewhere.
            let theirs = *x25519_dalek::StaticSecret::from(priv_key)
                .diffie_hellman(&x25519_dalek::PublicKey::from(p))
                .as_bytes();
            assert_eq!(
                theirs, [0u8; 32],
                "we call ({label}) {bad} small-order but dalek did not drive it to zero"
            );
        }
    }
}

/// Differential test against an audited implementation.
///
/// `x25519-dalek` is a **dev-dependency only** — it is never linked into the
/// shipped library. Not because it would be disastrous: the 2026-08-16 audit
/// measured its contribution at +0 distinct panic symbol names over a
/// no-dependency baseline, correcting a much-repeated "58 symbols" figure that
/// had counted `core`'s unreachable code. The reason is simply that
/// `fiat-crypto` is formally verified and costs nothing, so there is no call
/// for a second curve implementation in the artifact. As a test oracle this
/// one costs nothing and buys a great deal.
///
/// Fixed vectors prove a function agrees at a handful of points. The `fe_sub`
/// bug that shipped in the first draft of `x25519.rs` was self-consistent
/// under every round trip and only failed against a value computed elsewhere;
/// thousands of random agreements against audited code is the version of that
/// check which does not depend on having picked the right handful.
#[test]
fn x25519_agrees_with_an_audited_implementation() {
    use rand::RngCore;
    let mut rng = rand::thread_rng();

    for i in 0..512 {
        let mut sk = [0u8; 32];
        let mut pk = [0u8; 32];
        rng.fill_bytes(&mut sk);
        rng.fill_bytes(&mut pk);

        // Public keys derived from a scalar, compared against dalek.
        let ours_pub = public_key(&sk);
        let theirs_pub = *x25519_dalek::PublicKey::from(&x25519_dalek::StaticSecret::from(sk)).as_bytes();
        assert_eq!(ours_pub, theirs_pub, "public_key disagreed on iteration {i}");

        // And the agreement itself, against an arbitrary (possibly invalid)
        // point — the case where a sloppy reduction shows up.
        let theirs = *x25519_dalek::StaticSecret::from(sk)
            .diffie_hellman(&x25519_dalek::PublicKey::from(pk))
            .as_bytes();
        match x25519(&sk, &pk) {
            Some(ours) => assert_eq!(ours, theirs, "shared secret disagreed on iteration {i}"),
            None => assert_eq!(theirs, [0u8; 32], "we rejected a point dalek accepted, iteration {i}"),
        }
    }
}

/// Edge-case scalars and points, where reductions are most likely to be wrong.
#[test]
fn x25519_agrees_with_the_oracle_on_boundary_values() {
    let interesting: [[u8; 32]; 6] = [
        [0x00; 32],
        [0xFF; 32],
        {
            // p - 1
            let mut v = [0xFFu8; 32];
            v[0] = 0xEC;
            v[31] = 0x7F;
            v
        },
        {
            // p itself, which must reduce to zero
            let mut v = [0xFFu8; 32];
            v[0] = 0xED;
            v[31] = 0x7F;
            v
        },
        {
            let mut v = [0u8; 32];
            v[0] = 9;
            v
        },
        {
            let mut v = [0u8; 32];
            v[31] = 0x80;
            v
        },
    ];
    for (i, sk) in interesting.iter().enumerate() {
        for (j, pk) in interesting.iter().enumerate() {
            let theirs = *x25519_dalek::StaticSecret::from(*sk)
                .diffie_hellman(&x25519_dalek::PublicKey::from(*pk))
                .as_bytes();
            match x25519(sk, pk) {
                Some(ours) => assert_eq!(ours, theirs, "disagreed at ({i},{j})"),
                None => assert_eq!(theirs, [0u8; 32], "rejected a point dalek accepted at ({i},{j})"),
            }
        }
    }
}

/// FIPS-197 Appendix C.3 — the published AES-256 vector.
///
/// AES-256 was previously exercised only through one captured CCM message.
/// That would have caught a broken key schedule, but only because the tag
/// happened to fail; a primitive with a published vector should be checked
/// against it directly.
#[test]
fn aes256_matches_the_fips197_vector() {
    let mut key = [0u8; 32];
    key.copy_from_slice(&hex_to_bytes(
        "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
    ));
    let mut block = [0u8; 16];
    block.copy_from_slice(&hex_to_bytes("00112233445566778899aabbccddeeff"));
    Aes256::new(&key).encrypt_block(&mut block);
    assert_eq!(
        block.iter().map(|b| format!("{b:02x}")).collect::<String>(),
        "8ea2b7ca516745bfeafc49904b496089"
    );
}

/// AES-256-CCM against vectors from a different implementation.
///
/// Our CCM was checked against one captured message and against its own
/// round trip. The round trip cannot catch a systematic error — an encrypt
/// and decrypt that are wrong in the same way agree perfectly. These come
/// from elsewhere.
#[test]
fn ccm_matches_an_independent_implementation() {
    let cases: &[(&str, &str, &str, &str)] = &[
        ("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
         "a0a1a2a3a4a5a6a7a8a9aaabac", "", "b2fc18597a74bf1b"),
        ("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
         "a0a1a2a3a4a5a6a7a8a9aaabac", "01", "52baa6a959b7378917"),
        ("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
         "a0a1a2a3a4a5a6a7a8a9aaabac", "020f1c293643505d6a7784919eabb8c5",
         "51dffecc320c275794e231ac6e13b70a685092a72f67da13"),
        ("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
         "a0a1a2a3a4a5a6a7a8a9aaabac", "03101d2a3744515e6b7885929facb9c6d3",
         "50c0ffcf330b265495ed30af6f14b609a888d6ba19e212bc89"),
        ("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
         "a0a1a2a3a4a5a6a7a8a9aaabac",
         "04111e2b3845525f6c798693a0adbac7d4e1eefb0815222f3c495663707d8a97a4b1becbd8e5f2ff",
         "57c1fcce3c0a255592ec33ae5015b508af836cc9dea279c4cee9c9ee2b19f4d9c906d59aacdb66a02d71d12cb00b52f3"),
    ];
    for (k, n, pt, want) in cases {
        let mut key = [0u8; 32];
        key.copy_from_slice(&hex_to_bytes(k));
        let nonce = hex_to_bytes(n);
        let plain = hex_to_bytes(pt);

        let mut buf = vec![0u8; plain.len() + CCM_TAG_LEN];
        buf[..plain.len()].copy_from_slice(&plain);
        let total = ccm_encrypt_in_place(&key, &nonce, &mut buf, plain.len(), CCM_TAG_LEN).unwrap();
        assert_eq!(
            buf[..total].iter().map(|b| format!("{b:02x}")).collect::<String>(),
            *want,
            "encrypting {pt:?} disagreed with the reference"
        );

        // And back, so the decrypt path is checked against the same vector.
        let n2 = ccm_decrypt_in_place(&key, &nonce, &mut buf[..total], CCM_TAG_LEN).unwrap();
        assert_eq!(&buf[..n2], &plain[..]);
    }
}

/// The domain red list requires that a wrong channel hash must not decrypt.
///
/// Worth stating precisely, because the hash is not what protects anything:
/// it selects a key, and the wrong key yields garbage rather than an error.
/// Channel traffic has no tag, so **nothing here can tell you the frame was
/// not for you** — only that the bytes make no sense. That is the property
/// the extension suite's AEAD exists to supply.
#[test]
fn a_frame_from_another_channel_does_not_yield_its_plaintext() {
    let doc = fs::read_to_string(captures_dir().join("on_air_frames.json")).unwrap();
    let hex = json_str(&doc[doc.find("\"raw_hex\"").unwrap()..], "raw_hex").unwrap();
    let frame = hex_to_bytes(hex);
    let hdr = Header::decode(&frame).unwrap();

    // A different channel: same name, a PSK we invented.
    let Psk::Aes128(wrong) = expand_psk(&[0u8; 16]).unwrap() else { panic!() };
    assert_ne!(channel_hash(b"LongFast", &wrong), hdr.channel, "must be a different channel");

    let mut body = frame[HEADER_LEN..].to_vec();
    ctr_apply(&wrong, &nonce(hdr.id, hdr.from, 0), &mut body);
    assert!(
        !body.windows(11).any(|w| w == b"sniff-probe"),
        "the wrong key must not recover the plaintext"
    );
    // And the header still parses — routing works without the key, by design.
    assert_eq!(frame::peek_header(&frame).unwrap().hop_limit, 3);
}

/// The domain red list requires that an unknown PortNum is ignored, not fatal.
#[test]
fn an_unknown_portnum_is_carried_not_rejected() {
    let mut buf = [0u8; 64];
    let d = Data { portnum: 511, payload: b"future", ..Data::default() };
    let n = d.encode(&mut buf).expect("encoding an unknown port must work");
    let back = Data::decode(&buf[..n]).expect("decoding an unknown port must not fail");
    assert_eq!(back.portnum, 511, "PRIVATE_APP range must survive");
    assert_eq!(back.payload, b"future");

    // And a port number beyond anything defined today.
    let d2 = Data { portnum: 0x7FFF_FFFF, ..Data::default() };
    let n2 = d2.encode(&mut buf).unwrap();
    assert_eq!(Data::decode(&buf[..n2]).unwrap().portnum, 0x7FFF_FFFF);
}

/// A second differential oracle: formally verified code derived from HACL*.
///
/// `x25519-dalek` and `libcrux-curve25519` are independent implementations,
/// and agreeing with both is a stronger claim than agreeing with either. This
/// one is additionally the output of a verified pipeline, so where it agrees
/// with ours the algorithm and constants are corroborated by a proof we did
/// not have to reproduce.
///
/// It is an oracle and never a dependency: it requires a global allocator,
/// which `DISTRIBUTION.md` forbids in the shipped library. A test binary has
/// std, so nothing is given up here.
#[test]
fn x25519_agrees_with_a_formally_verified_implementation() {
    use rand::RngCore;
    let mut rng = rand::thread_rng();

    for i in 0..256 {
        let mut sk = [0u8; 32];
        let mut pk = [0u8; 32];
        rng.fill_bytes(&mut sk);
        rng.fill_bytes(&mut pk);

        let mut theirs = [0u8; 32];
        let ok = libcrux_curve25519::ecdh(&mut theirs, &pk, &sk).is_ok();

        match x25519(&sk, &pk) {
            Some(ours) => {
                assert!(ok, "we accepted a point the verified code rejected, iteration {i}");
                assert_eq!(ours, theirs, "disagreed with verified code, iteration {i}");
            }
            None => assert!(!ok, "we rejected a point the verified code accepted, iteration {i}"),
        }

        // Public keys too.
        let mut theirs_pub = [0u8; 32];
        libcrux_curve25519::secret_to_public(&mut theirs_pub, &sk);
        assert_eq!(public_key(&sk), theirs_pub, "public_key disagreed, iteration {i}");
    }
}

// ===========================================================================
// The hardware-accelerator seam.
//
// `backend.rs` had no callers and no tests until these were written, which is
// how two defects survived in it: no way for a fallible part to report
// failure, and no way to name a key it holds but will not surrender. Both are
// invisible to a test that only ever exercises software.
//
// So these do not test AES or SHA — those are covered elsewhere against
// published vectors. They test the *seam*: that a partial override falls
// through, that failure is reportable, and that the three ways an operation
// can fail stay distinguishable.
// ===========================================================================

/// A backend that accelerates exactly one primitive. `backend.rs` claims this
/// is "a short `impl` with one method"; this is that claim, compiled.
struct OnlySha;

impl Backend for OnlySha {
    fn sha256(&self, _data: &[u8]) -> Result<[u8; 32], BackendError> {
        Ok([0xA5; 32])
    }
}

/// A backend whose silicon is unhappy. The old seam could not express this at
/// all: `sha256` returned `[u8; 32]`, so a part that failed had to invent a
/// digest or panic.
struct Wedged;

impl Backend for Wedged {
    fn sha256(&self, _data: &[u8]) -> Result<[u8; 32], BackendError> {
        Err(BackendError::Hardware)
    }
}

#[test]
fn the_software_backend_agrees_with_the_bare_function() {
    let a = [7u8; 32];
    let b = [9u8; 32];
    let (pa, pb) = (public_key(&a), public_key(&b));

    let sw = Software;
    let ours = sw.x25519(SecretKey::Bytes(&a), &pb).expect("agreement");
    let theirs = sw.x25519(SecretKey::Bytes(&b), &pa).expect("agreement");

    assert_eq!(ours, theirs, "the two sides did not agree");
    assert_eq!(
        ours,
        x25519(&a, &pb).expect("bare agreement"),
        "routing through the seam changed the answer"
    );
    assert_eq!(
        sw.public_key(SecretKey::Bytes(&a)).expect("public key"),
        pa,
        "seam public_key disagreed with the bare one"
    );
}

#[test]
fn software_refuses_a_key_it_cannot_hold() {
    // Key custody is the whole reason `SecretKey` exists. Software has none,
    // and the failure that matters is the quiet one: accepting a slot number
    // and agreeing a secret with some *other* key would be far worse than
    // refusing.
    let sw = Software;
    let peer = public_key(&[3u8; 32]);

    assert_eq!(
        sw.x25519(SecretKey::Slot(2), &peer),
        Err(BackendError::Unsupported),
        "software claimed a key slot it does not have"
    );
    assert_eq!(
        sw.public_key(SecretKey::Slot(2)),
        Err(BackendError::Unsupported),
        "software produced a public key for a slot it does not have"
    );
}

#[test]
fn a_small_order_peer_is_not_a_hardware_fault() {
    // These were the same value once: `x25519` returned `Option`, so a
    // backend reporting an I2C timeout was indistinguishable from one
    // reporting an active attack. One is retryable; the other must never be.
    let sw = Software;
    let err = sw.x25519(SecretKey::Bytes(&[1u8; 32]), &[0u8; 32]).unwrap_err();

    assert_eq!(err, BackendError::SmallOrderPeer, "small-order peer misreported");
    assert_ne!(err, BackendError::Hardware, "an attack was reported as a retryable fault");
}

#[test]
fn overriding_one_primitive_leaves_the_others_alone() {
    let acc = OnlySha;
    let sw = Software;

    assert_eq!(acc.sha256(b"anything").expect("digest"), [0xA5; 32], "override did not take");

    // ...and the primitive it did *not* override still works, identically to
    // software. This is the fall-through the per-primitive design promises.
    let key = [0x11u8; 16];
    let iv = [0x22u8; 16];
    let (mut via_acc, mut via_sw) = ([0u8; 40], [0u8; 40]);

    acc.aes_ctr(&key, &iv, &mut via_acc).expect("ctr via partial backend");
    sw.aes_ctr(&key, &iv, &mut via_sw).expect("ctr via software");

    assert_eq!(via_acc, via_sw, "inherited default diverged from software");
    assert_ne!(via_acc, [0u8; 40], "keystream was all zeros — nothing happened");
}

#[test]
fn a_backend_can_report_that_its_hardware_failed() {
    assert_eq!(
        Wedged.sha256(b"anything"),
        Err(BackendError::Hardware),
        "hardware failure was not reportable"
    );
    // And it did not have to invent a digest to say so.
    assert!(Wedged.sha256(b"anything").is_err(), "a wedged part returned an answer");
}

#[test]
fn a_bad_tag_is_never_reported_as_a_hardware_fault() {
    // Conflating these would let a caller retry its way past authentication.
    let key = [0x44u8; 32];
    let nonce = [0x55u8; 13];
    let sw = Software;

    let mut buf = [0u8; 16 + CCM_TAG_LEN];
    for (i, b) in buf.iter_mut().take(16).enumerate() {
        *b = i as u8;
    }
    let n = sw.ccm_seal(&key, &nonce, &mut buf, 16, CCM_TAG_LEN).expect("seal");

    // Flip a bit in the tag.
    buf[n - 1] ^= 0x01;

    let err = sw.ccm_open(&key, &nonce, &mut buf[..n], CCM_TAG_LEN).unwrap_err();
    assert_eq!(err, BackendError::Ccm(CcmError::Unauthentic), "forgery misreported");
    assert_ne!(err, BackendError::Hardware, "a forgery was reported as retryable");
}
