//! Host-side tests.
//!
//! These run against the committed corpus in `tests/captures/` rather than
//! against hard-coded copies of it. That is deliberate: a vector table
//! transcribed into a test drifts from the capture it came from, and the
//! drift is invisible because both sides still agree with themselves.
//!
//! `tools/check_rust_rules.sh` exempts `*/tests/*` from the no-panic rules.
//! An assertion is a panic, and that is what an assertion is for.

use std::fs;
use std::path::PathBuf;

use tethermesh::channel::channel_hash;
use tethermesh::message::{ChannelSettings, Data, PortNum, User};
use tethermesh::packet_id::{NextId, PacketIdSource};
use tethermesh::protobuf::{Error as ProtoError, Reader, Value, Writer};

fn captures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/captures")
}

/// Extract a quoted string field from a JSON object slice.
///
/// A deliberately small scanner rather than a JSON dependency: the corpus is
/// generated by us in a known shape, and `Cargo.toml` records that adding a
/// dependency has to clear a bar this does not need to clear.
fn json_str<'a>(obj: &'a str, key: &str) -> Option<&'a str> {
    let at = obj.find(&format!("\"{key}\""))?;
    let rest = obj.get(at.checked_add(key.len())?.checked_add(2)?..)?;
    let colon = rest.find(':')?;
    let after = rest.get(colon.checked_add(1)?..)?;
    let open = after.find('"')?;
    let body = after.get(open.checked_add(1)?..)?;
    let close = body.find('"')?;
    body.get(..close)
}

/// Extract an unsigned integer field from a JSON object slice.
fn json_u32(obj: &str, key: &str) -> Option<u32> {
    let at = obj.find(&format!("\"{key}\""))?;
    let rest = obj.get(at.checked_add(key.len())?.checked_add(2)?..)?;
    let colon = rest.find(':')?;
    let after = rest.get(colon.checked_add(1)?..)?;
    let digits: String = after
        .chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(char::is_ascii_digit)
        .collect();
    digits.parse().ok()
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    assert!(hex.len() % 2 == 0, "odd-length hex string: {hex:?}");
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("corpus contains non-hex in psk_hex"))
        .collect()
}

/// Split the corpus into the object slices that describe one vector each.
///
/// Vector objects are the ones carrying `psk_hex`; the provenance and
/// verified-properties blocks do not, so keying on it avoids having to
/// understand the surrounding structure.
fn vector_objects(doc: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut from = 0usize;
    while let Some(hit) = doc[from..].find("\"psk_hex\"") {
        let abs = from + hit;
        let start = doc[..abs].rfind('{').expect("psk_hex outside any object");
        let end = abs + doc[abs..].find('}').expect("unterminated object");
        out.push(&doc[start..=end]);
        from = end;
    }
    out
}

#[test]
fn channel_hash_matches_every_committed_vector() {
    let path = captures_dir().join("channel_hash.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let objects = vector_objects(&doc);
    assert!(
        objects.len() >= 6,
        "corpus shrank to {} vectors — a test that silently checks less is worse \
         than one that fails",
        objects.len()
    );

    let mut observed = 0usize;
    for obj in &objects {
        let name = json_str(obj, "name").expect("vector has no name");
        let psk_hex = json_str(obj, "psk_hex").expect("vector has no psk_hex");
        let expected = json_u32(obj, "expected_hash").expect("vector has no expected_hash");
        let kind = json_str(obj, "kind").unwrap_or("unspecified");

        let got = channel_hash(name.as_bytes(), &hex_to_bytes(psk_hex));
        assert_eq!(
            u32::from(got),
            expected,
            "channel_hash({name:?}, {psk_hex}) = 0x{got:02x}, corpus says 0x{expected:02x}"
        );
        if kind == "oracle-observed" {
            observed = observed.saturating_add(1);
        }
    }

    // The synthetic rows are computed from the same function under test, so
    // on their own they prove only self-consistency. The oracle-observed rows
    // are the ones that tie this implementation to the reference, and losing
    // them would gut the test without failing it.
    assert!(
        observed >= 2,
        "only {observed} oracle-observed vector(s) — the synthetic rows cannot \
         substitute, they are generated from this same function"
    );
}

/// Collect every `"hex": "..."` value in a document, in order.
fn all_hex(doc: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut from = 0usize;
    while let Some(hit) = doc[from..].find("\"hex\"") {
        let abs = from + hit;
        let rest = &doc[abs..];
        if let Some(v) = json_str(rest, "hex") {
            out.push(v);
        }
        from = abs + 5;
    }
    out
}

/// L3's gate, run against the reference implementation's own output.
///
/// Every message in the corpus was encoded by their encoder. Decoding it and
/// re-encoding it must reproduce the bytes exactly — not an equivalent
/// encoding, the same one. This is only an achievable requirement because
/// their encoder was measured to be canonical: minimal varints, fields in
/// ascending order. Had it been otherwise, byte-identity would have been
/// impossible and the gate itself would have needed rewriting.
#[test]
fn every_corpus_message_round_trips_bit_identically() {
    let path = captures_dir().join("fromradio_corpus.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let messages = all_hex(&doc);
    assert!(
        messages.len() >= 40,
        "corpus holds only {} messages — a gate that silently checks less is \
         not a gate",
        messages.len()
    );

    let mut total = 0usize;
    for (i, hex) in messages.iter().enumerate() {
        let original = hex_to_bytes(hex);

        let mut fields = Vec::new();
        let mut reader = Reader::new(&original);
        while let Some(field) = reader
            .next_field()
            .unwrap_or_else(|e| panic!("message {i}: decode failed: {e:?}\n  {hex}"))
        {
            fields.push(field);
        }
        assert!(!fields.is_empty(), "message {i} decoded to no fields");

        let mut out = vec![0u8; original.len()];
        let written = {
            let mut writer = Writer::new(&mut out);
            for field in &fields {
                writer
                    .field(field.number, &field.value)
                    .unwrap_or_else(|e| panic!("message {i}: encode failed: {e:?}"));
            }
            writer.len()
        };

        assert_eq!(
            written,
            original.len(),
            "message {i}: re-encoded to {written} bytes, original was {}",
            original.len()
        );
        assert_eq!(
            out, original,
            "message {i} did not round-trip bit-identically\n  original: {hex}\n  re-encoded: {}",
            out.iter().map(|b| format!("{b:02x}")).collect::<String>()
        );
        total = total.saturating_add(1);
    }
    assert_eq!(total, messages.len());
}

/// Round-trip `bytes`, then recurse into any length-delimited field that is
/// itself well-formed protobuf. Returns how many messages were checked.
///
/// Nesting has to be probed rather than known: at the wire layer a
/// length-delimited field may be a string, a byte blob or a nested message,
/// and nothing distinguishes them. Recursing wherever the bytes happen to
/// parse is sound for an identity check — if a string parses as a message and
/// re-encodes to itself, the assertion still holds — and it reaches real
/// nested messages, which is the point.
fn roundtrip_deep(bytes: &[u8], depth: usize, path: &str) -> usize {
    assert!(depth < 16, "{path}: nesting deeper than 16, refusing to recurse");

    let mut fields = Vec::new();
    let mut reader = Reader::new(bytes);
    loop {
        match reader.next_field() {
            Ok(Some(f)) => fields.push(f),
            Ok(None) => break,
            // Not a message at this level; nothing to check here.
            Err(_) => return 0,
        }
    }
    if fields.is_empty() {
        return 0;
    }

    let mut out = vec![0u8; bytes.len()];
    let written = {
        let mut writer = Writer::new(&mut out);
        for f in &fields {
            if writer.field(f.number, &f.value).is_err() {
                return 0;
            }
        }
        writer.len()
    };
    if written != bytes.len() {
        return 0;
    }
    assert_eq!(
        out, bytes,
        "{path}: nested message did not round-trip bit-identically"
    );

    let mut checked = 1usize;
    for f in &fields {
        if let Value::Len(inner) = f.value {
            if !inner.is_empty() {
                let child = format!("{path}/{}", f.number);
                checked = checked.saturating_add(roundtrip_deep(inner, depth + 1, &child));
            }
        }
    }
    checked
}

/// The gate again, but all the way down.
///
/// The property measured at capture time was top-level. This extends it to
/// every nested message the corpus contains, which is where a real encoder
/// bug would hide: a length prefix recomputed one byte differently is
/// invisible at the outer level because the outer length still matches.
#[test]
fn nested_messages_round_trip_bit_identically() {
    let path = captures_dir().join("fromradio_corpus.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let mut checked = 0usize;
    for (i, hex) in all_hex(&doc).iter().enumerate() {
        checked = checked.saturating_add(roundtrip_deep(&hex_to_bytes(hex), 0, &format!("msg{i}")));
    }
    // Strictly more than the 43 top-level messages, or the recursion never
    // reached anything and this test is checking the previous one again.
    assert!(
        checked > 43,
        "only {checked} messages checked — recursion found no nested messages, \
         so this adds nothing over the top-level gate (expected ~100 against \
         43 top-level)"
    );
}

/// `User` against real bytes the reference produced.
///
/// The corpus is `FromRadio`; field 4 is `node_info`, and `NodeInfo` field 2
/// is a `User`. Lifting it out gives a wrapper test tied to the reference
/// rather than to our own encoder's opinion of itself.
#[test]
fn user_wrapper_round_trips_reference_bytes() {
    let path = captures_dir().join("fromradio_corpus.json");
    let doc = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let mut seen = 0usize;
    for hex in all_hex(&doc) {
        let msg = hex_to_bytes(hex);
        let mut reader = Reader::new(&msg);
        while let Ok(Some(field)) = reader.next_field() {
            // FromRadio.node_info = 4
            let Value::Len(node_info) = field.value else { continue };
            if field.number != 4 {
                continue;
            }
            let mut inner = Reader::new(node_info);
            while let Ok(Some(nf)) = inner.next_field() {
                // NodeInfo.user = 2
                let Value::Len(user_bytes) = nf.value else { continue };
                if nf.number != 2 {
                    continue;
                }
                let user = User::decode(user_bytes).expect("reference User failed to decode");
                assert!(!user.id.is_empty(), "decoded User has no id");
                assert!(!user.long_name.is_empty(), "decoded User has no long_name");

                let mut out = vec![0u8; user_bytes.len()];
                let n = user.encode(&mut out).expect("re-encoding User failed");
                assert_eq!(
                    (n, &out[..n]),
                    (user_bytes.len(), user_bytes),
                    "User did not re-encode to the reference bytes"
                );
                seen = seen.saturating_add(1);
            }
        }
    }
    assert!(seen >= 1, "corpus contained no NodeInfo.user to test against");
}

#[test]
fn data_wrapper_round_trips() {
    let original = Data {
        portnum: PortNum::TEXT_MESSAGE_APP.0,
        payload: b"hello mesh",
        want_response: true,
        dest: 0x1234_5678,
        request_id: 0xdead_beef,
        bitfield: Some(1),
        ..Data::default()
    };
    let mut buf = [0u8; 128];
    let n = original.encode(&mut buf).expect("encode failed");
    let decoded = Data::decode(&buf[..n]).expect("decode failed");
    assert_eq!(decoded, original);

    let mut again = [0u8; 128];
    let m = decoded.encode(&mut again).expect("re-encode failed");
    assert_eq!(&buf[..n], &again[..m], "wrapper encoding is not stable");
}

/// Proto3 omits defaults, and so must we.
///
/// An explicit zero decodes to the same message but is a different byte
/// string, which would fail a comparison against reference output.
#[test]
fn wrapper_omits_default_valued_fields() {
    let mut buf = [0u8; 64];
    let n = Data::default().encode(&mut buf).expect("encode failed");
    assert_eq!(n, 0, "an all-default Data encoded to {n} bytes, expected 0");

    // `bitfield` is declared `optional`, so it has real presence: Some(0) is
    // not the same as absent, and must survive.
    let explicit_zero = Data { bitfield: Some(0), ..Data::default() };
    let n = explicit_zero.encode(&mut buf).expect("encode failed");
    assert!(n > 0, "an explicitly-set optional field was dropped as if absent");
    assert_eq!(Data::decode(&buf[..n]).expect("decode failed").bitfield, Some(0));
}

/// The documented limitation, asserted so it cannot change silently.
///
/// The wrapper drops fields it does not know. That is fine for reading a
/// frame and wrong for forwarding one, which is why the module documentation
/// says a relay path must not go through this layer. If this test ever fails,
/// the architecture note needs rewriting too.
#[test]
fn wrapper_drops_unknown_fields_and_the_primitive_layer_does_not() {
    // A Data with a plausible future field 15 that this build knows nothing of.
    let mut crafted = [0u8; 64];
    let n = {
        let mut w = Writer::new(&mut crafted);
        w.field(1, &Value::Varint(1)).unwrap();
        w.field(2, &Value::Len(b"hi")).unwrap();
        w.field(15, &Value::Varint(0x2a)).unwrap();
        w.len()
    };
    let original = &crafted[..n];

    let mut via_wrapper = [0u8; 64];
    let m = Data::decode(original)
        .expect("decode failed")
        .encode(&mut via_wrapper)
        .expect("encode failed");
    assert!(m < n, "expected the unknown field to be dropped, but nothing was lost");

    // The primitive layer keeps it, which is why relaying belongs there.
    // A floor rather than an exact count: `roundtrip_deep` recurses wherever
    // bytes happen to parse, and the two-byte payload "hi" is itself valid
    // protobuf, so it descends one level further than the crafted nesting.
    assert!(roundtrip_deep(original, 0, "crafted") >= 1);
}

/// The output buffer is caller-provided, so running out of room is an
/// ordinary outcome and must be reported rather than panicked on.
#[test]
fn encoding_into_a_short_buffer_reports_rather_than_panics() {
    let mut tiny = [0u8; 1];
    let mut writer = Writer::new(&mut tiny);
    let err = writer.field(1, &Value::Len(b"more than one byte")).unwrap_err();
    assert_eq!(err, ProtoError::BufferTooSmall);
}

/// Malformed input comes from the mesh, so every one of these must be an
/// error and none of them a panic. This is the negative twin of the
/// round-trip gate.
#[test]
fn malformed_input_errors_and_never_panics() {
    let cases: &[(&str, &[u8])] = &[
        ("truncated length-delimited", &[0x0a, 0x05, 0x01]),
        ("varint never terminates", &[0x08, 0x80, 0x80, 0x80]),
        ("varint longer than 64 bits", &[
            0x08, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x02,
        ]),
        ("group wire type 3", &[0x0b]),
        ("unassigned wire type 7", &[0x0f]),
        ("field number zero", &[0x00, 0x01]),
        ("truncated fixed32", &[0x0d, 0x01, 0x02]),
        ("truncated fixed64", &[0x09, 0x01, 0x02, 0x03]),
    ];
    for (name, bytes) in cases {
        let mut reader = Reader::new(bytes);
        // Drain: the error may surface on any field, not only the first.
        let errored = loop {
            match reader.next_field() {
                Ok(Some(_)) => continue,
                Ok(None) => break false,
                Err(_) => break true,
            }
        };
        assert!(
            errored,
            "{name}: accepted malformed input {bytes:02x?} instead of rejecting it"
        );
    }
}

#[test]
fn channel_hash_is_order_independent_within_each_input() {
    // XOR folding cannot distinguish orderings. Asserted rather than left
    // implicit, because it is a real property of the wire format: two
    // channel names that are anagrams share a hash, and anything that treats
    // a hash match as identification is wrong for reasons this test states.
    let psk = [0xAAu8, 0xBB, 0xCC];
    assert_eq!(channel_hash(b"abc", &psk), channel_hash(b"cba", &psk));
}

#[test]
fn empty_inputs_are_meaningful_not_invalid() {
    assert_eq!(channel_hash(b"", b""), 0);
    assert_eq!(channel_hash(b"\x5a", b""), 0x5a);
    assert_eq!(channel_hash(b"", b"\x5a"), 0x5a);
}


/// `ChannelSettings` against reference bytes, and the hash it feeds.
///
/// The corpus carries `FromRadio.channel` (10) holding a `Channel`, whose
/// `settings` (2) is a `ChannelSettings`. Re-encoding must be byte-identical,
/// and the primary channel's settings must produce the channel hash the
/// oracle was observed to use.
#[test]
fn channel_settings_round_trip_and_feed_the_verified_hash() {
    let doc = fs::read_to_string(captures_dir().join("fromradio_corpus.json")).unwrap();

    let mut checked = 0usize;
    let mut primary_hash = None;
    for hex in all_hex(&doc) {
        let msg = hex_to_bytes(hex);
        let mut reader = Reader::new(&msg);
        while let Ok(Some(field)) = reader.next_field() {
            let Value::Len(channel) = field.value else { continue };
            if field.number != 10 {
                continue;
            }
            let mut inner = Reader::new(channel);
            while let Ok(Some(cf)) = inner.next_field() {
                let Value::Len(settings_bytes) = cf.value else { continue };
                if cf.number != 2 {
                    continue;
                }
                let settings =
                    ChannelSettings::decode(settings_bytes).expect("settings failed to decode");

                let mut out = vec![0u8; settings_bytes.len()];
                let n = settings.encode(&mut out).expect("settings failed to encode");
                assert_eq!(
                    (n, &out[..n]),
                    (settings_bytes.len(), settings_bytes),
                    "ChannelSettings did not re-encode to the reference bytes"
                );
                checked = checked.saturating_add(1);

                // The default primary channel stores the PSK as the single
                // byte 0x01 — a short index, not a key. Expanded here to the
                // key the oracle was observed to use, which is the only form
                // the hash is defined over.
                if settings.psk == [0x01] {
                    let expanded =
                        hex_to_bytes("d4f1bb3a20290759f0bcffabcf4e6901");
                    let name = if settings.name.is_empty() {
                        b"LongFast".as_slice()
                    } else {
                        settings.name
                    };
                    primary_hash = Some(channel_hash(name, &expanded));
                }
            }
        }
    }
    assert!(checked >= 1, "corpus contained no ChannelSettings");
    assert_eq!(
        primary_hash,
        Some(0x08),
        "the primary channel's settings did not produce the hash the oracle used"
    );
}

/// Simulate a node that reboots at arbitrary, hostile moments.
///
/// Returns every identifier it managed to transmit. The rule modelled is the
/// one that matters: an identifier counts as used the moment it is handed
/// out, and a crash may occur between a durable write and the next write, or
/// part-way through a block, or immediately after resuming.
fn run_with_reboots(seed: u32, block: u32, reboots: &[usize]) -> Vec<u32> {
    let mut issued = Vec::new();
    // What survived the last crash. Only ever what was actually written.
    let mut durable = seed;

    for &packets_before_crash in reboots {
        let mut src = PacketIdSource::resume(durable, block);
        let mut sent = 0usize;
        while sent < packets_before_crash {
            match src.issue() {
                NextId::Ready(id) => {
                    issued.push(id);
                    sent += 1;
                }
                NextId::PersistFirst { high_water } => {
                    // The write lands, then is acknowledged. This is the only
                    // point at which `durable` may move.
                    durable = high_water;
                    src.persisted(high_water);
                }
                NextId::Exhausted => return issued,
            }
        }
        // Crash here: anything reserved-but-unissued is lost, and `durable`
        // keeps whatever was last written.
    }
    issued
}

/// PLAN's L2 requirement, stated there as: no `(packet_id, sender)` pair
/// repeats across a simulated reboot.
///
/// The sender is fixed for a given node, so the pair repeats exactly when the
/// identifier does. Under CTR that reissues a keystream, and the published
/// documentation says an attacker who deduces one plaintext can then forge
/// using the pair without the PSK. So this is a forgery test, not a
/// uniqueness nicety.
#[test]
fn packet_ids_never_repeat_across_reboots() {
    // Reboot after wildly varying numbers of packets, including 0 and values
    // that land mid-block and exactly on block boundaries.
    let schedules: &[&[usize]] = &[
        &[0, 1, 1, 1, 1],
        &[5, 5, 5, 5, 5],
        &[256, 1, 255, 257, 3],
        &[1000, 1, 1, 999],
        &[7, 0, 13, 0, 1, 512],
    ];
    for (n, schedule) in schedules.iter().enumerate() {
        for &block in &[1u32, 4, 256] {
            let ids = run_with_reboots(0, block, schedule);
            let unique: std::collections::HashSet<u32> = ids.iter().copied().collect();
            assert_eq!(
                unique.len(),
                ids.len(),
                "schedule {n} block {block}: {} identifiers issued, {} distinct — \
                 a repeat reissues a CTR keystream",
                ids.len(),
                unique.len()
            );
        }
    }
}

/// Identifiers are only issued below a mark that is already durable.
///
/// This is the property that makes the reboot test hold for reboots that
/// were not simulated, rather than only for the schedules listed above.
#[test]
fn no_id_is_issued_beyond_what_was_persisted() {
    let mut src = PacketIdSource::resume(0, 8);
    let mut durable: Option<u32> = None;
    for _ in 0..64 {
        match src.issue() {
            NextId::Ready(id) => {
                let mark = durable.expect("issued an identifier before anything was persisted");
                assert!(
                    id < mark,
                    "issued {id} but only {mark} is durable — an unclean restart would reissue it"
                );
            }
            NextId::PersistFirst { high_water } => {
                durable = Some(high_water);
                src.persisted(high_water);
            }
            NextId::Exhausted => break,
        }
    }
}

/// A stale or replayed confirmation must not move the mark backwards.
#[test]
fn a_stale_persist_confirmation_cannot_reopen_used_ids() {
    let mut src = PacketIdSource::resume(100, 16);
    let NextId::PersistFirst { high_water } = src.issue() else {
        panic!("expected a reservation first")
    };
    src.persisted(high_water);
    let NextId::Ready(first) = src.issue() else {
        panic!("expected an identifier")
    };

    src.persisted(0);
    src.persisted(high_water.saturating_sub(8));
    assert_eq!(src.reserved_until(), high_water, "the mark moved backwards");

    let NextId::Ready(second) = src.issue() else {
        panic!("expected an identifier")
    };
    assert!(second > first);
}

/// Exhaustion is reported, not wrapped.
///
/// Wrapping would reissue every identifier from the beginning, which is
/// precisely the failure this type exists to prevent.
#[test]
fn exhaustion_is_reported_rather_than_wrapping() {
    let mut src = PacketIdSource::resume(u32::MAX, 16);
    let mut saw_exhausted = false;
    for _ in 0..8 {
        match src.issue() {
            NextId::Exhausted => {
                saw_exhausted = true;
                break;
            }
            NextId::PersistFirst { high_water } => src.persisted(high_water),
            NextId::Ready(id) => assert_eq!(id, u32::MAX, "issued past the end of the space"),
        }
    }
    assert!(saw_exhausted, "ran off the end of the identifier space without saying so");
}
